/* Kenko 1st Organic — multilingual e-book content.
   Add a language by adding a BOOK.<code> object with the same shape. */
window.HERB_EN=['Organic Amla Powder','Ashwagandha Powder','Heenbovitiya Powder','Katupila Powder','Lunuwila (Bacopa) Powder','Thulsi (Holy Basil) Powder','Yakinaran Powder','Kothala Himbutu Powder','Neeramulliya Powder','Papaya Leaves Powder','Ranawara Flower Powder','Rasakinda Powder','Soursop Leaves','Thebu Powder','Polpala Powder','Organic Cinnamon Powder','Organic Ginger Powder','Organic Moringa Powder','Iramusu Powder'];
window.FOOD_EN=['Kurakkan (Finger Millet) Flour','Kithul Flour','Organic Green Gram','Organic Red Cowpea','Organic White Cowpea','Suwandal Rice','Bee Honey','Kithul Treacle','Rice Flakes','Organic Dry Mango','Organic Dry Pineapple','Organic Dry Banana','Dried Jackfruit (Waraka)'];
window.BOOK={};

BOOK.si={
 guide:'ජීවන අත්පොත', coverTitle:'පොළොවෙන් මේසයට', coverSub:'වස විෂෙන් තොර, කාබනික ජීවිතයක් වෙනුවෙන්', coverBlurb:'පිරිසිදු ආහාර, කාබනික නිෂ්පාදනවල වටිනාකම සහ ස්වාභාවික ඖෂධ පැළෑටිවල සුවය පිළිබඳ කුඩා පොතකි.',
 fwKick:'පෙරවදන', fwTitle:'කුඩා තේරීමක්, විශාල වෙනසක්', fwLead:'අප දිනපතා තෝරාගන්නා ආහාරය, අපගේ සෞඛ්‍යය, පොළොව සහ එන පරම්පරාව හැඩගස්වයි. මෙය එම තේරීම් සරලව, අවංකව කතා කරන කුඩා පොතකි.', fwP2:'රසායනික පොහොර සහ කෘමිනාශක වලින් තොරව වැඩුණු ආහාරයක වටිනාකම, ස්වාභාවික ඖෂධ පැළෑටිවල සුවය සහ ඒවා එදිනෙදා ජීවිතයට එක් කරගන්නා ආකාරය මෙහි ඇතුළත් වේ.', fwP3:'මෙය ආරාධනාවකි — වස විෂෙන් තොර ආහාර තෝරා ගැනීමට, කාබනික පොළොව අපට දෙන දෑ අගය කිරීමට, සහ එන පරම්පරාවට වඩා නිරෝගී ලෝකයක් ඉතිරි කිරීමට.',
 tocKick:'පටුන', tocTitle:'මෙම පොතේ', tocFoot:'කෙටි පරිච්ඡේද පහක්. පිළිවෙළින් කියවන්න, නැතහොත් අවශ්‍ය තැනට පෙරළන්න.',
 toc:[{n:'1',t:'වස විෂෙන් තොර ආහාරයේ වැදගත්කම',p:'04',go:3},{n:'2',t:'කාබනික ආහාරවල වටිනාකම',p:'07',go:6},{n:'3',t:'අනාගත පරම්පරාව වෙනුවෙන්',p:'10',go:9},{n:'4',t:'ස්වාභාවික ඖෂධ පැළෑටි',p:'13',go:12},{n:'5',t:'ධාන්‍ය, පිටි හා වියළි පලතුරු',p:'33',go:32}],
 c1Label:'පළමු පරිච්ඡේදය', c1Title:'වස විෂෙන් තොර<br>ආහාරයේ වැදගත්කම', c1Sub:'අප ගන්නා දේ, අප වෙයි',
 c1H:'අප ගන්නා දේ, අප වෙයි', c1Lead:'වාණිජ වගාවන්හි බහුලව භාවිත වන කෘමිනාශක සහ රසායනික පොහොර, අස්වැන්නත් සමඟ අපගේ ශරීරයට ද ඇතුළු වේ.', c1P2:'මෙම රසායනික ද්‍රව්‍ය කුඩා ප්‍රමාණවලින් වුවද දිගු කලක් තිස්සේ ශරීරගත වීමෙන් ආහාර ජීර්ණය, හෝමෝන සමතුලිතතාව සහ ප්‍රතිශක්තිකරණ පද්ධතියට බලපෑම් ඇති කළ හැකි බව පර්යේෂණ පෙන්වා දෙයි.', c1P3:'වස විෂෙන් තොර ආහාරයක් තෝරා ගැනීම යනු මෙම අනවශ්‍ය බර ශරීරයෙන් ඉවත් කිරීමකි. එය ලෙඩක් සුව කිරීමට වඩා, ලෙඩක් ඇති නොවීමට කරන ආයෝජනයකි.',
 q1Kick:'මතක තබාගන්න', q1Quote:'“ඔබේ ආහාරය ඖෂධයක් වේවා — නැතහොත් ඔබේ ඖෂධය ආහාරය වේවා.”', q1Sub:'දිනකට තුන්වරක් ඔබ ගන්නා තේරීම ඔබ සතු සරලම ආරක්ෂාවයි.',
 c2Label:'දෙවන පරිච්ඡේදය', c2Title:'කාබනික ආහාරවල<br>වටිනාකම', c2Sub:'සජීවී පොළොවක දීමනාව',
 c2H:'සජීවී පොළොවක දීමනාව', c2Lead:'කාබනික වගාවක වටිනාකම ආරම්භ වන්නේ පොළොවෙනි. සජීවී, පෝෂ්‍යදායී පසක වැඩෙන ශාකයක් වැඩි පෝෂ්‍ය ගුණයක් රැගෙන එයි.', c2P2:'රසායනික නොවන පොහොර සහ සොබාදහමේ ක්‍රම මගින් රැක බලාගත් පසෙහි ක්ෂුද්‍ර ජීවීන් සහ පෝෂක බහුලය. එය එළවළු සහ පලතුරුවලට ස්වාභාවික රසය, සුවඳ සහ දිගු කල් තැබීමේ හැකියාව ලබා දෙයි.', c2P3:'එමෙන්ම කාබනික වගාව ජලය, පස සහ ජෛව විවිධත්වය ආරක්ෂා කරයි — එනම් අප ගන්නා සෑම තේරීමක්ම පරිසරයටත් දීමනාවකි.',
 c2ImgKick:'නැවුම්', c2ImgTitle:'රසය ද, ගුණය ද — දෙකම වැඩිය.',
 c3Label:'තෙවන පරිච්ඡේදය', c3Title:'අනාගත පරම්පරාව<br>වෙනුවෙන්', c3Sub:'අප ඉතිරි කරන ලෝකය',
 c3H:'අප ඉතිරි කරන ලෝකය', c3Lead:'අප දරුවන්ට ඉතිරි කරන්නේ මුදල් හෝ දේපළ පමණක් නොවේ — අප ඔවුන්ට ඉතිරි කරන්නේ පොළොවක්, ජලයක් සහ ආහාර සංස්කෘතියක් ද වේ.', c3P2:'දරුවන්ට හොඳ ආහාර ලබා දිය යුත්තේ ඇයි? මන්ද ඔවුන්ගේ වර්ධනය, මොළයේ ක්‍රියාකාරිත්වය සහ අනාගත සෞඛ්‍යය අද ඔවුන් ගන්නා ආහාරය මත ගොඩනැගෙන බැවිනි.', c3P3:'රසායනික මත රඳා නොපවතින, සොබාදහමට ගරු කරන වගා ක්‍රමයක් අනුගමනය කිරීම යනු — අපගේ දරුවන්ට ද, ඔවුන්ගේ දරුවන්ට ද පෝෂණය කළ හැකි පොළොවක් තිරසාරව රැක ගැනීමකි.',
 c3StepKick:'කුඩා පියවර', c3StepTitle:'අද කළ හැකි දේ', c3StepFoot:'වෙනස විශාල විය යුතු නැත. එය ආරම්භ විය යුතුය.',
 c3Steps:[{t:'① කාබනික තෝරන්න',b:'සතියකට එක් වේලක්වත් රසායනික නොවන එළවළු වෙත මාරු වන්න.'},{t:'② දේශීය මිලදී ගන්න',b:'ආසන්න ගොවියාගෙන් හෝ විශ්වාසනීය කඩයකින් ගැනීම නැවුම්කම සහ ගුණය රකී.'},{t:'③ පොඩි වගාවක්',b:'ගෙදර මුල්ලක කරපිංචා, ගොටුකොළ වගා කිරීමෙන් පටන් ගන්න.'}],
 c4Label:'සිව්වන පරිච්ඡේදය', c4Title:'ස්වාභාවික<br>ඖෂධ පැළෑටි', c4Sub:'සොබාදහමේ ඖෂධ', c4Blurb:'සොබාදහම අපට දුන් ඖෂධ පැළෑටි කිහිපයක් — ඒවායේ ගුණය සහ භාවිත කරන ආකාරය මෙතැන් සිට.',
 c5Label:'පස්වන පරිච්ඡේදය', c5Title:'ධාන්‍ය, පිටි හා<br>වියළි පලතුරු', c5Sub:'දිනපතා පෝෂණය', c5Blurb:'දිනපතා ආහාරයට එක් කළ හැකි පෝෂ්‍යදායී ධාන්‍ය, පිටි වර්ග සහ ස්වාභාවික කෙටි කෑම.',
 itemHerbCat:'ඖෂධ පැළෑටි', itemFoodCat:'ධාන්‍ය හා ආහාර', labBenefit:'සිරුරට ඇති වටිනාකම', labUse:'භාවිතා කරන ආකාරය', labTip:'දැනගන්න', photoPh:'පින්තූරය',
 closeKick:'Kenko 1st Organic', closeTitle:'සොබාදහමේ ගුණය,<br>ඔබේ මේසයට', closeTagline:'Live a healthy life · Think next generation', closeBlurb:'වස විෂෙන් තොර, කාබනික නිෂ්පාදන සඳහා අප හමුවන්න. සෑම නිෂ්පාදනයක්ම සොබාදහමට හා ඔබේ පවුලට ගරු කරමින් තෝරාගෙන ඇත.',
 contact:['ලිපිනය · Address','දුරකථන · Phone','වෙබ් · Web'],
 hint:'පිටුවේ දෙපැත්තට ක්ලික් කරන්න · ← → · පිටු පෙරළන්න',
 herbs:[
  {name:'නෙල්ලි',b:'ලෝකයේ විටමින් C බහුලම ආහාර අතර නෙල්ලි ඉදිරියෙන් සිටී. එය ප්‍රතිශක්තිය ශක්තිමත් කරමින් ජීර්ණයට උදව් වන අතර, ප්‍රතිඔක්සිකාරක බහුල බැවින් හම හා කෙස් නිරෝගීව තබා ගනී.',u:'තේ හැන්දක් උණුවතුර හෝ මී පැණි සමඟ මිශ්‍ර කර උදෑසන හිස් බඩට ගන්න. ස්මූති හෝ පලතුරු යුෂ වලට ද එක් කළ හැක.',t:['ප්‍රතිශක්තිය','විටමින් C','කෙස් හා හම'],k:'දිනකට තේ හැන්දක් නිතිපතා ගැනීමෙන් හොඳ ප්‍රතිඵල ලැබේ.'},
  {name:'අශ්වගන්ධා',b:'මානසික ආතතිය හා තෙහෙට්ටුව අඩු කරන "ඇඩප්ටජන්" ඖෂධයකි. ශක්තිය, නින්දේ ගුණය හා ඒකාග්‍රතාව වැඩි කරන අතර ශරීරයේ ස්වාභාවික ප්‍රතිරෝධය ගොඩනගයි.',u:'රාත්‍රියේ නින්දට පෙර උණුකළ කිරි වීදුරුවකට තේ හැඳි භාගයක් මිශ්‍ර කර පානය කරන්න.',t:['ආතතිය අඩු','ශක්තිය','හොඳ නින්ද'],k:'අඛණ්ඩව සති කිහිපයක් ගැනීමෙන් ආතතිය කළමනාකරණයට උදව් වේ.'},
  {name:'හීන්බෝවිටිය',b:'රුධිර සීනි මට්ටම පාලනයට හා ශරීරයේ විෂ ද්‍රව්‍ය ඉවත් කිරීමට සම්ප්‍රදායික දේශීය වෛද්‍යවේදයේ බහුලව යොදාගනී. හම ආශ්‍රිත ගැටලු වලට ද හිතකරයි.',u:'තේ හැන්දක් උණුවතුරට දමා කසායක් ලෙස පිළියෙළ කර ගන්න.',t:['රුධිර සීනි','ශරීර පිරිසිදුව','හම'],k:'දියවැඩියා රෝගීන් වෛද්‍ය උපදෙස් සමඟ භාවිත කිරීම සුදුසුයි.'},
  {name:'කටුපිල',b:'ශරීරයේ විෂ ඉවත් කිරීමට හා වකුගඩු සෞඛ්‍යයට සම්ප්‍රදායික වෛද්‍ය ක්‍රමයේ ඉහළින් වටිනා පැළෑටියකි. රුධිර සීනි පාලනයට ද යොදාගැනේ.',u:'කසායක් ලෙස පිළියෙළ කර නිර්දේශිත මාත්‍රාවෙන් ගන්න.',t:['විෂ ඉවත්','වකුගඩු','රුධිර සීනි'],k:'සම්ප්‍රදායිකව අගය කරන දේශීය ඖෂධ පැළෑටියකි.'},
  {name:'ලුණුවිල',b:'මතක ශක්තිය, ඒකාග්‍රතාව හා මොළයේ ක්‍රියාකාරිත්වය වර්ධනයට ලොව පුරා ප්‍රසිද්ධ පැළෑටියකි. ස්නායු සන්සුන් කර ආතතිය අඩු කරයි.',u:'මී පැණි හෝ කිරි සමඟ තේ හැන්දක් ගන්න; ඉගෙනුම් වයසේ දරුවන්ට ද සුදුසුයි.',t:['මතකය','මොළය','ස්නායු'],k:'උගන්නා දරුවන්ට හිතකර සම්ප්‍රදායික ඖෂධයකි.'},
  {name:'තුල්සි (මාදුරුතලා)',b:'කැස්ස, සෙම්ප්‍රතිශ්‍යාව හා ශ්වසන අපහසුතා සමනය කරන පූජනීය ශාකයකි. ප්‍රතිශක්තිය වර්ධනය කරමින් ආතතිය ද අඩු කරයි.',u:'උණුවතුරට දමා තුල්සි තේ එකක් ලෙස පානය කරන්න; මී පැණි ද එක් කළ හැක.',t:['කැස්ස/සෙම','ප්‍රතිශක්තිය','ශ්වසනය'],k:'උදෑසන තේ එකක් ලෙස ගැනීම සුව පහසුය.'},
  {name:'යකිනාරන්',b:'උණ, කැස්ස හා රුධිර පවිත්‍රතාවයට සම්ප්‍රදායිකව භාවිත වන ඖෂධයකි. ශරීරය සිසිල් කරන ගුණ ඇත.',u:'කසායක් ලෙස පිළියෙළ කර ගන්න.',t:['උණ','රුධිර පවිත්‍ර','සිසිල්'],k:'දේශීය වෙදකමේ පැරණි ඖෂධ පැළෑටියකි.'},
  {name:'කොත්තල හිඹුටු',b:'රුධිර සීනි මට්ටම පාලනයට හා බර කළමනාකරණයට ලොව පුරා ප්‍රසිද්ධ සම්ප්‍රදායික ඖෂධයකි. සීනි අවශෝෂණය මන්දගාමී කරන බව විශ්වාස කෙරේ.',u:'ආහාරයට පෙර උණුවතුරේ දිය කර ගන්න.',t:['රුධිර සීනි','බර පාලනය','දියවැඩියා'],k:'ආහාරයට මිනිත්තු 30කට පෙර ගැනීම යෝග්‍යයි.'},
  {name:'නීරමුල්ලිය',b:'මුත්‍රා පද්ධතිය, වකුගඩු හා අක්මා සෞඛ්‍යයට හිතකර පැළෑටියකි. ශරීරයේ අනවශ්‍ය ජලය ඉවත් කිරීමට උදව් වේ.',u:'කසායක් ලෙස පිළියෙළ කර ගන්න.',t:['වකුගඩු','මුත්‍රා පද්ධතිය','අක්මාව'],k:'ජලය හොඳින් පානය කරමින් භාවිත කරන්න.'},
  {name:'පැපොල් කොළ',b:'රුධිර පට්ටිකා (platelets) වර්ධනයට හා ජීර්ණ පද්ධතියට හිතකර බව සම්ප්‍රදායිකව විශ්වාස කෙරේ. ඩෙංගු සුවවීමේදී ද බහුලව යොදාගැනේ.',u:'වතුර වීදුරුවකට සුළු ප්‍රමාණයක් දමා ගන්න; යුෂ ලෙස ද ගත හැක.',t:['රුධිර පට්ටිකා','ජීර්ණය','ඩෙංගු'],k:'දරුණු රෝගී තත්ත්ව වලදී වෛද්‍ය උපදෙස් ලබා ගන්න.'},
  {name:'රණවරා මල්',b:'රුධිර සීනි පාලනයට හා හම පිරිසිදු කිරීමට හිතකර, කැෆේන් රහිත තේ වෙනුවට ගත හැකි මල් වර්ගයකි. ශරීරය සිසිල් කරයි.',u:'උණුවතුරට දමා රණවරා තේ එකක් ලෙස පානය කරන්න.',t:['රුධිර සීනි','හම','තේ විකල්පය'],k:'උදෑසන කැෆේන් රහිත පානයක් ලෙස කදිමයි.'},
  {name:'රසකිඳ',b:'ප්‍රතිශක්තිය, උණ හා සන්ධි සෞඛ්‍යයට ආයුර්වේදයේ "අමෘතය" ලෙස සැලකෙන ඖෂධයකි. ශරීරයේ ප්‍රතිරෝධය ගොඩනගයි.',u:'කසායක් ලෙස පිළියෙළ කර ගන්න.',t:['ප්‍රතිශක්තිය','උණ','සන්ධි'],k:'ආයුර්වේදයේ "ගුඩුචි" ලෙස ප්‍රසිද්ධයි.'},
  {name:'කටුඅනෝදා කොළ',b:'ප්‍රතිඔක්සිකාරක බහුල, නින්දට හා ප්‍රතිශක්තියට හිතකර බව විශ්වාස කෙරේ. ශරීරය සන්සුන් කරයි.',u:'කොළ උණුවතුරේ තම්බා තේ එකක් ලෙස රාත්‍රියේ ගන්න.',t:['ප්‍රතිඔක්සිකාරක','නින්ද','ප්‍රතිශක්තිය'],k:'රාත්‍රී තේ එකක් ලෙස ගැනීම සුව පහසුය.'},
  {name:'තෙබු',b:'රුධිර සීනි හා කොලෙස්ටරෝල් පාලනයට හිතකර සම්ප්‍රදායික පැළෑටියකි. දියවැඩියා කළමනාකරණයට බහුලව යොදාගැනේ.',u:'ආහාරයට එක් කර හෝ වතුර සමඟ ගන්න; නැවුම් කොළ සලාද ලෙස ද ගත හැක.',t:['රුධිර සීනි','කොලෙස්ටරෝල්','දියවැඩියා'],k:'"දියවැඩියා පැළෑටිය" ලෙස ජනප්‍රියයි.'},
  {name:'පොල්පලා',b:'වකුගඩු ගල්, මුත්‍රා අපහසුතා සමනයට හා ශරීරය සිසිල් කිරීමට සම්ප්‍රදායිකව භාවිත වේ. ශරීරයේ අනවශ්‍ය තාපය අඩු කරයි.',u:'කසායක් ලෙස හෝ පොල්පලා කැඳක් ලෙස පිළියෙළ කර ගන්න.',t:['වකුගඩු','මුත්‍රා','සිසිල්'],k:'පොල්පලා කැඳ සම්ප්‍රදායික සුව ආහාරයකි.'},
  {name:'කුරුඳු',b:'රුධිර සීනි සමතුලනයට හිතකර, ප්‍රතිඔක්සිකාරක බහුල සුවඳැති කුළුබඩුවකි. ශ්‍රී ලාංකික "සැබෑ කුරුඳු" ලොව හොඳම ලෙස සැලකේ.',u:'තේ, කිරි හෝ ආහාර පිසීමේදී එක් කරන්න; කේක් හා පුඩිං වලට ද සුදුසුයි.',t:['රුධිර සීනි','සුවඳ','ප්‍රතිඔක්සිකාරක'],k:'Ceylon Cinnamon ලොව අගය කරන දේශීය නිෂ්පාදනයකි.'},
  {name:'ඉඟුරු',b:'ජීර්ණයට උදව් වන, ඔක්කාරය හා සෙම්ප්‍රතිශ්‍යාව සමනය කරන ප්‍රදාහ නාශක කුළුබඩුවකි. ශරීරය උණුසුම් කරයි.',u:'තේ එකට, ආහාර පිසීමට හෝ උණුවතුරට දමා ගන්න.',t:['ජීර්ණය','ප්‍රදාහ නාශක','සෙම'],k:'ඉඟුරු තේ එකක් සීතල දිනවලට කදිමයි.'},
  {name:'මුරුංගා',b:'විටමින්, යකඩ, කැල්සියම්, ප්‍රෝටීන් හා ප්‍රතිඔක්සිකාරක බහුල පෝෂ්‍යදායී "සුපිරි ආහාරයකි". ශක්තිය හා ප්‍රතිශක්තිය වර්ධනය කරයි.',u:'සුප්, ව්‍යාංජන, කැඳ හෝ ස්මූති වලට තේ හැන්දක් එක් කරන්න.',t:['පෝෂණය','යකඩ','ප්‍රෝටීන්'],k:'"අත්භූත ගස" ලෙස ලොව පුරා ප්‍රසිද්ධයි.'},
  {name:'ඉරමුසු',b:'ශරීරය සිසිල් කරන, රුධිරය පවිත්‍ර කරන හා හම සෞඛ්‍යයට හිතකර සුවඳැති මුල් වර්ගයකි. පිපාසය සංසිඳුවයි.',u:'උණුවතුරට හෝ සීතල වතුරට දමා පානයක් ලෙස ගන්න.',t:['සිසිල්','රුධිර පවිත්‍ර','හම'],k:'ඉරමුසු පානය උණුසුම් දිනවලට ප්‍රබෝධමත්.'},
 ],
 foods:[
  {name:'කුරක්කන් පිටි',b:'කැල්සියම්, යකඩ හා තන්තු බහුල, අඩු GI ධාන්‍ය පිටියකි. දියවැඩියාවට හිතකර අතර දරුවන්ගේ අස්ථි වර්ධනයට ද උපකාරී වේ.',u:'රොටි, පිට්ටු, කැඳ, තලප හෝ පෑන්කේක් ලෙස පිළියෙළ කරන්න.',t:['කැල්සියම්','තන්තු','අඩු GI'],k:'උදෑසන කුරක්කන් කැඳ ශක්තිජනක ආහාරයකි.'},
  {name:'කිතුල් පිටි',b:'සම්ප්‍රදායික, ශක්තිය ලබා දෙන අඩු GI ස්වාභාවික පිටියකි. සිරුර සිසිල් කරන ගුණ ඇතැයි විශ්වාස කෙරේ.',u:'තලප, කැඳ හෝ පැණිරස ආහාර ලෙස පිළියෙළ කරන්න.',t:['ශක්තිය','අඩු GI','සම්ප්‍රදායික'],k:'කිතුල් තලප දේශීය ප්‍රිය ආහාරයකි.'},
  {name:'මුං ඇට',b:'පහසුවෙන් ජීර්ණය වන, ප්‍රෝටීන් හා ශක්තිය බහුල ධාන්‍යයකි. ශරීරය සිසිල් කරන අතර සැහැල්ලුයි.',u:'තම්බා, කැඳ ලෙස හෝ රසකැවිලි වලට යොදාගන්න.',t:['ප්‍රෝටීන්','සැහැල්ලු','ශක්තිය'],k:'තම්බපු මුං උදෑසන ආහාරයට කදිමයි.'},
  {name:'රතු කවුපි',b:'ප්‍රෝටීන්, තන්තු හා යකඩ බහුල පිරී තිබෙන ධාන්‍යයකි. දිගු වේලාවක් බඩ පිරී තබා ගනී.',u:'තම්බා පොල් සමඟ උදෑසන ආහාරයට හෝ ව්‍යාංජන ලෙස ගන්න.',t:['ප්‍රෝටීන්','යකඩ','තන්තු'],k:'උදෑසන ශක්තිජනක ආහාරයකි.'},
  {name:'සුදු කවුපි',b:'ප්‍රෝටීන් හා තන්තු බහුල, සෞඛ්‍ය සම්පන්න ධාන්‍යයකි. රුධිර සීනි සෙමින් මුදාහරින බැවින් දිගු ශක්තියක් දෙයි.',u:'තම්බා පොල් සමඟ උදෑසන ආහාරයට ගන්න.',t:['ප්‍රෝටීන්','තන්තු','දිගු ශක්තිය'],k:'පොල් සමඟ තම්බා ගැනීම රසවත්.'},
  {name:'සුවඳැල් හාල්',b:'සුවඳැති, පෝෂ්‍යදායී සම්ප්‍රදායික දේශීය සහල් වර්ගයකි. සුවිශේෂී සුවඳක් හා රසයක් ඇත.',u:'බත්, කිරිබත් හෝ විශේෂ අවස්ථා ආහාර ලෙස පිළියෙළ කරන්න.',t:['සුවඳ','දේශීය','පෝෂණය'],k:'උත්සව අවස්ථා වලට විශේෂ සහල් වර්ගයකි.'},
  {name:'මී පැණි',b:'සීනි වෙනුවට භාවිත කළ හැකි ස්වාභාවික මිහිරි ද්‍රව්‍යයකි. උගුරේ අපහසුතා, කැස්ස සමනයට හා ප්‍රතිශක්තියට හිතකරයි.',u:'උණුවතුර, තේ, පලතුරු හෝ ආහාර වලට සීනි වෙනුවට එක් කරන්න.',t:['ස්වාභාවික මිහිර','උගුර','ප්‍රතිශක්තිය'],k:'උණුවතුර සමඟ මී පැණි උදෑසන පානයක් ලෙස ගන්න.'},
  {name:'කිතුල් පැණි',b:'ඛනිජ බහුල, අඩු GI ස්වාභාවික මිහිරි ද්‍රව්‍යයකි. පිරිපහදු සීනි වලට වඩා සෞඛ්‍ය සම්පන්නයි.',u:'ආප්ප, කිරි, පලතුරු මත වත් කර හෝ සීනි වෙනුවට යොදාගන්න.',t:['අඩු GI','ඛනිජ','ස්වාභාවික'],k:'ආප්ප හා කිරි සමඟ දේශීය ප්‍රිය රසයකි.'},
  {name:'රයිස් ෆ්ලේක්ස්',b:'පහසුවෙන් ශක්තිය ලබා දෙන, ඉක්මනින් ජීර්ණය වන සැහැල්ලු ආහාරයකි. කාර්යබහුල උදෑසන වලට කදිමයි.',u:'කිරි, කිරි දී, පොල් හෝ මී පැණි සමඟ මිශ්‍ර කර ගන්න.',t:['ඉක්මන් ශක්තිය','සැහැල්ලු','පහසු'],k:'මිනිත්තු කිහිපයකින් සූදානම් කළ හැකි ආහාරයකි.'},
  {name:'වියළි අඹ',b:'විටමින්, තන්තු හා ප්‍රතිඔක්සිකාරක බහුල, එකතු කළ සීනි රහිත ස්වාභාවික කෙටි කෑමකි. කෘත්‍රිම කෑම වලට සෞඛ්‍ය සම්පන්න විකල්පයකි.',u:'සෘජුවම කෙටි කෑමක් ලෙස රස විඳින්න; ධාන්‍ය හෝ යෝගට් වලට ද එක් කළ හැක.',t:['සීනි රහිත','විටමින්','ස්නැක්'],k:'දරුවන්ගේ ලන්ච් බොක්ස් වලට සෞඛ්‍ය සම්පන්නයි.'},
  {name:'වියළි අන්නාසි',b:'විටමින් C හා ජීර්ණ එන්සයිම බහුල ස්වාභාවික කෙටි කෑමකි. එකතු කළ කෘත්‍රිම දෑ රහිතයි.',u:'සෘජුවම ස්නැක් එකක් ලෙස ගන්න.',t:['විටමින් C','ජීර්ණය','ස්නැක්'],k:'රසවත් ස්වාභාවික පැණිරසක්.'},
  {name:'වියළි කෙසෙල්',b:'පොටෑසියම් හා ශක්තිය බහුල ස්වාභාවික කෙටි කෑමකි. ව්‍යායාමයෙන් පසු ශක්තිය නැවත ලබා ගැනීමට කදිමයි.',u:'සෘජුවම හෝ ධාන්‍ය සමඟ මිශ්‍ර කර ගන්න.',t:['පොටෑසියම්','ශක්තිය','ස්නැක්'],k:'ක්‍රීඩකයන්ට ස්වාභාවික ශක්ති කෑමක්.'},
  {name:'වියළි වරකා',b:'ඉදුණු වරකා මද, රසායනික හෝ කෘත්‍රිම සීනි එක් නොකර අව්වේ හෝ අඩු තාපයෙන් වියළා සාදන ලද ස්වාභාවික කෙටි කෑමකි. තන්තු, පොටෑසියම් හා ස්වාභාවික ශක්තිය බහුල අතර ජීර්ණයට හිතකර වේ. වාරය ඉවර වුණත් වසර පුරා වරකා රසය භුක්ති විඳිය හැක.',u:'කෙටි කෑමක් ලෙස එලෙසම කන්න, නැතහොත් කිරි, ධාන්‍ය හෝ අතුරුපස සමඟ මිශ්‍ර කරන්න. වියළි, වාතය නොවදින භාජනයක ගබඩා කරන්න.',t:['තන්තු','ස්වාභාවික ශක්තිය','කෙටි කෑම'],k:'ශ්‍රී ලංකාවේ "බත් ගස" ලෙස හඳුන්වන කොස් ගසේ ඉදුණු ඵලයයි.'},
 ],
};

BOOK.en={
 guide:'A Guide to Living Well', coverTitle:'From Soil to Table', coverSub:'For a clean, organic life free of poison', coverBlurb:'A little book on clean food, the value of organic produce, and the healing of natural herbs.',
 fwKick:'Foreword', fwTitle:'A small choice, a big difference', fwLead:'The food we choose each day shapes our health, our soil and the generation to come. This is a little book about those choices, told simply and honestly.', fwP2:'It covers the value of food grown without chemical fertiliser or pesticide, the healing found in natural herbs, and how to bring them into everyday life.', fwP3:'This book is a gentle invitation — to choose food grown without poison, to value what organic soil gives us, and to pass a healthier world to those who follow.',
 tocKick:'Contents', tocTitle:'In this book', tocFoot:'Five short chapters. Read them in order, or turn straight to what you need.',
 toc:[{n:'1',t:'Why food free of poison matters',p:'04',go:3},{n:'2',t:'The value of organic food',p:'07',go:6},{n:'3',t:'For the generations to come',p:'10',go:9},{n:'4',t:'Natural herbs',p:'13',go:12},{n:'5',t:'Grains, flours & dried fruits',p:'33',go:32}],
 c1Label:'Chapter One', c1Title:'Why food free<br>of poison matters', c1Sub:'We become what we eat',
 c1H:'We become what we eat', c1Lead:'The pesticides and chemical fertilisers used widely in commercial farming enter our bodies along with the harvest.', c1P2:'Research shows that even in small amounts, taken in over a long time, these chemicals can affect digestion, hormone balance and the immune system.', c1P3:'Choosing food free of poison means lifting that unnecessary burden from the body. It is less about curing illness than about not inviting it in.',
 q1Kick:'Remember', q1Quote:'“Let food be thy medicine, and medicine be thy food.”', q1Sub:'The simplest protection you own is the choice you make three times a day.',
 c2Label:'Chapter Two', c2Title:'The value of<br>organic food', c2Sub:'The gift of living soil',
 c2H:'The gift of living soil', c2Lead:'The value of an organic crop begins in the soil. A plant grown in living, nourishing earth carries more nourishment.', c2P2:'Soil cared for with natural methods, free of chemical fertiliser, teems with microbes and nutrients. This gives vegetables and fruit their natural taste, aroma and keeping quality.', c2P3:'Organic farming also protects water, soil and biodiversity — so every choice we make is a gift to the environment too.',
 c2ImgKick:'Fresh', c2ImgTitle:'More taste, and more goodness.',
 c3Label:'Chapter Three', c3Title:'For the generations<br>to come', c3Sub:'The world we leave behind',
 c3H:'The world we leave behind', c3Lead:'We leave our children more than money or property — we leave them a soil, a water, and a food culture.', c3P2:'Why give children good food? Because their growth, their minds and their future health are built on what they eat today.', c3P3:'Following a way of farming that respects nature, rather than one dependent on chemicals, means sustainably keeping a soil that can nourish our children and theirs.',
 c3StepKick:'Small steps', c3StepTitle:'What you can do today', c3StepFoot:'Change does not need to be large. It needs to begin.',
 c3Steps:[{t:'① Choose organic',b:'Switch to chemical-free vegetables for even one meal a week.'},{t:'② Buy local',b:'Buying from a nearby farmer or a trusted shop keeps freshness and quality.'},{t:'③ Grow a little',b:'Start with karapincha or gotukola in a corner of your garden.'}],
 c4Label:'Chapter Four', c4Title:'Natural<br>herbs', c4Sub:"Nature's medicine", c4Blurb:'A handful of the herbs nature gave us — their benefits, and how to use them, from here on.',
 c5Label:'Chapter Five', c5Title:'Grains, flours &<br>dried fruits', c5Sub:'Everyday nourishment', c5Blurb:'Nourishing grains, flours and natural snacks to bring into your daily meals.',
 itemHerbCat:'Herbal', itemFoodCat:'Wholefood', labBenefit:'Value to the body', labUse:'How to use it', labTip:'Good to know', photoPh:'Image',
 closeKick:'Kenko 1st Organic', closeTitle:"Nature's goodness,<br>on your table", closeTagline:'Live a healthy life · Think next generation', closeBlurb:'Come to us for clean, organic products, free of poison. Every product is chosen with respect for nature and for your family.',
 contact:['Address','Phone','Web'],
 hint:'Click the page edges · ← → keys · to turn the page',
 herbs:[
  {name:'Indian Gooseberry (Amla)',b:"Amla is one of the world's richest sources of vitamin C. It strengthens immunity and aids digestion, and its antioxidants help keep skin and hair healthy.",u:'Mix a teaspoon into warm water or honey and take on an empty stomach each morning; it also blends well into smoothies.',t:['Immunity','Vitamin C','Hair & skin'],k:'A steady daily teaspoon gives the best results.'},
  {name:'Ashwagandha',b:"An adaptogenic herb that helps reduce stress and fatigue. It supports energy, restful sleep and focus while building the body's natural resilience.",u:'Stir half a teaspoon into a glass of warm milk before bed.',t:['Less stress','Energy','Better sleep'],k:'Taken consistently for a few weeks, it helps with stress management.'},
  {name:'Heenbovitiya',b:'Widely used in traditional medicine to help manage blood sugar and cleanse the body. It is also considered beneficial for the skin.',u:'Stir a teaspoon into hot water and drink as a herbal decoction.',t:['Blood sugar','Cleansing','Skin'],k:'Those with diabetes should use it alongside medical advice.'},
  {name:'Katupila',b:'A herb prized in traditional medicine for detoxifying the body and supporting kidney health. It is also used to help manage blood sugar.',u:'Prepare as a decoction and take in the recommended dose.',t:['Detox','Kidneys','Blood sugar'],k:'Long valued as a household medicinal plant.'},
  {name:'Lunuwila (Bacopa)',b:'Famous worldwide for supporting memory, focus and brain function. It also calms the nerves and eases stress.',u:'Take a teaspoon with honey or milk; suitable for school-age children too.',t:['Memory','Brain','Nerves'],k:'A traditional favourite for growing, studying children.'},
  {name:'Thulsi (Holy Basil)',b:'A sacred plant that soothes cough, colds and respiratory discomfort. It boosts immunity and helps reduce stress.',u:'Steep in hot water and drink as thulsi tea; add honey if you like.',t:['Cough/cold','Immunity','Breathing'],k:'A morning cup is a gentle, soothing ritual.'},
  {name:'Yakinaran',b:'Traditionally used for fever, cough and purifying the blood. It has cooling properties for the body.',u:'Prepare as a decoction and drink.',t:['Fever','Blood purifier','Cooling'],k:'An old remedy of indigenous medicine.'},
  {name:'Kothala Himbutu',b:'A traditional remedy known worldwide for managing blood sugar and weight. It is believed to slow the absorption of sugar.',u:'Dissolve in warm water and take before meals.',t:['Blood sugar','Weight','Diabetes'],k:'Best taken about 30 minutes before a meal.'},
  {name:'Neeramulliya',b:'Beneficial for the urinary system, kidneys and liver. It helps flush excess water from the body.',u:'Prepare as a decoction and drink.',t:['Kidneys','Urinary','Liver'],k:'Use while drinking plenty of water.'},
  {name:'Papaya Leaf',b:'Traditionally believed to support blood platelet levels and digestion. Widely used during recovery from dengue.',u:'Add a small amount to a glass of water; can also be taken as juice.',t:['Platelets','Digestion','Dengue'],k:'Seek medical advice in serious illness.'},
  {name:'Ranawara Flower',b:'A caffeine-free tea alternative that supports blood sugar and clear skin. It cools the body.',u:'Steep in hot water and drink as ranawara tea.',t:['Blood sugar','Skin','Tea swap'],k:'A lovely caffeine-free morning drink.'},
  {name:'Rasakinda (Guduchi)',b:'Called "the nectar" in Ayurveda for supporting immunity and easing fever and joint pain. It builds the body\'s resistance.',u:'Prepare as a decoction and drink.',t:['Immunity','Fever','Joints'],k:'Known as "Guduchi" in Ayurveda.'},
  {name:'Soursop Leaf',b:'Rich in antioxidants and believed to support sleep and immunity. It calms the body.',u:'Simmer the leaves in hot water and drink as a tea in the evening.',t:['Antioxidants','Sleep','Immunity'],k:'A soothing night-time tea.'},
  {name:'Thebu',b:'A traditional herb that supports healthy blood sugar and cholesterol. Widely used in managing diabetes.',u:'Add to food or take with water; the fresh leaves can be eaten in salads.',t:['Blood sugar','Cholesterol','Diabetes'],k:'Popular as the "diabetes plant".'},
  {name:'Polpala',b:'Traditionally used to ease kidney stones and urinary discomfort and to cool the body. It reduces excess internal heat.',u:'Prepare as a decoction or as polpala porridge.',t:['Kidneys','Urinary','Cooling'],k:'Polpala porridge is a traditional healing food.'},
  {name:'Ceylon Cinnamon',b:'A fragrant spice, rich in antioxidants, that supports balanced blood sugar. Sri Lankan "true cinnamon" is regarded as the world\'s finest.',u:'Add to tea, milk or cooking; lovely in cakes and puddings.',t:['Blood sugar','Aroma','Antioxidants'],k:'Ceylon Cinnamon is a prized local product.'},
  {name:'Ginger',b:'An anti-inflammatory spice that aids digestion and eases nausea and colds. It warms the body.',u:'Add to tea, cooking, or stir into warm water.',t:['Digestion','Anti-inflammatory','Colds'],k:'Ginger tea is perfect on cold days.'},
  {name:'Moringa',b:'A nutrient-dense "superfood" rich in vitamins, iron, calcium, protein and antioxidants. It builds energy and immunity.',u:'Add a teaspoon to soups, curries, porridge or smoothies.',t:['Nutrition','Iron','Protein'],k:'Known worldwide as "the miracle tree".'},
  {name:'Iramusu',b:'A fragrant root that cools the body, purifies the blood and supports healthy skin. It quenches thirst.',u:'Add to warm or cold water and drink as a refreshing beverage.',t:['Cooling','Blood purifier','Skin'],k:'An iramusu drink is refreshing on hot days.'},
 ],
 foods:[
  {name:'Finger Millet (Kurakkan)',b:'A low-GI flour rich in calcium, iron and fibre. Friendly for diabetes and helpful for children\'s bone growth.',u:'Make into roti, pittu, porridge, thalapa or pancakes.',t:['Calcium','Fibre','Low GI'],k:'Morning kurakkan porridge is an energising meal.'},
  {name:'Kithul Flour',b:'A traditional, low-GI natural flour that provides steady energy. Believed to have cooling properties.',u:'Prepare as thalapa, porridge or sweet dishes.',t:['Energy','Low GI','Traditional'],k:'Kithul thalapa is a beloved local dish.'},
  {name:'Green Gram (Mung)',b:'An easily digested grain rich in protein and energy. Light on the stomach and cooling for the body.',u:'Boil, make into porridge, or use in sweets.',t:['Protein','Light','Energy'],k:'Boiled mung makes a great breakfast.'},
  {name:'Red Cowpea',b:'A filling grain rich in protein, fibre and iron. It keeps you full for longer.',u:'Boil with coconut for breakfast, or cook as a curry.',t:['Protein','Iron','Fibre'],k:'An energising morning meal.'},
  {name:'White Cowpea',b:'A wholesome grain rich in protein and fibre. It releases sugar slowly for lasting energy.',u:'Boil with coconut and enjoy for breakfast.',t:['Protein','Fibre','Lasting energy'],k:'Delicious boiled with coconut.'},
  {name:'Suwandal Rice',b:'A fragrant, nutritious traditional heritage rice with a distinctive aroma and taste.',u:'Cook as rice, milk-rice, or for special-occasion meals.',t:['Aroma','Heritage','Nutrition'],k:'A special rice for festive occasions.'},
  {name:'Bee Honey',b:'A natural sweetener to replace sugar. Soothing for the throat and cough, and supportive of immunity.',u:'Add to warm water, tea, fruit or food in place of sugar.',t:['Natural sweet','Throat','Immunity'],k:'Honey in warm water makes a fine morning drink.'},
  {name:'Kithul Treacle',b:'A mineral-rich, low-GI natural sweetener. Healthier than refined sugar.',u:'Pour over hoppers, curd or fruit, or use in place of sugar.',t:['Low GI','Minerals','Natural'],k:'A beloved local pairing with hoppers and curd.'},
  {name:'Rice Flakes',b:'A light, quickly digested food that gives easy energy. Perfect for busy mornings.',u:'Mix with milk, curd, coconut or honey.',t:['Quick energy','Light','Easy'],k:'Ready in just a few minutes.'},
  {name:'Dried Mango',b:'A natural snack rich in vitamins, fibre and antioxidants, with no added sugar. A healthy swap for processed treats.',u:'Enjoy on its own, or add to cereal or yoghurt.',t:['No added sugar','Vitamins','Snack'],k:"A healthy addition to children's lunch boxes."},
  {name:'Dried Pineapple',b:'A natural snack rich in vitamin C and digestive enzymes, with nothing artificial added.',u:'Enjoy straight as a snack.',t:['Vitamin C','Digestion','Snack'],k:'A tasty, naturally sweet treat.'},
  {name:'Dried Banana',b:'A natural snack rich in potassium and energy. Great for refuelling after exercise.',u:'Enjoy on its own or mix with cereal.',t:['Potassium','Energy','Snack'],k:'A natural energy snack for athletes.'},
  {name:'Dried Jackfruit',b:'Ripe jackfruit bulbs dried in the sun or at low heat, with no chemicals or added sugar. Rich in fibre, potassium and natural energy, and gentle on digestion. It keeps the taste of jackfruit season all year round.',u:'Enjoy straight as a snack, or add to milk, cereal or desserts. Store in a dry, airtight jar.',t:['Fibre','Natural energy','Snack'],k:'Made from the ripe fruit of the jack tree, known in Sri Lanka as the "rice tree".'},
 ],
};

BOOK.ta={
 guide:'நல்வாழ்வுக்கான கையேடு', coverTitle:'மண்ணிலிருந்து மேசைக்கு', coverSub:'விஷமற்ற, இயற்கை வாழ்விற்காக', coverBlurb:'சுத்தமான உணவு, இயற்கை விளைபொருட்களின் மதிப்பு, இயற்கை மூலிகைகளின் நலம் பற்றிய ஒரு சிறு நூல்.',
 fwKick:'முன்னுரை', fwTitle:'சிறிய தேர்வு, பெரிய மாற்றம்', fwLead:'நாம் தினமும் தேர்ந்தெடுக்கும் உணவு நமது ஆரோக்கியத்தையும் மண்ணையும் வரும் தலைமுறையையும் வடிவமைக்கிறது. அந்தத் தேர்வுகளைப் பற்றி எளிமையாகவும் நேர்மையாகவும் பேசும் ஒரு சிறு நூல் இது.', fwP2:'இரசாயன உரம், பூச்சிக்கொல்லி இல்லாமல் வளர்க்கப்படும் உணவின் மதிப்பு, இயற்கை மூலிகைகளின் நலம், அவற்றை அன்றாட வாழ்வில் சேர்த்துக்கொள்ளும் வழிகள் இதில் அடங்கும்.', fwP3:'இது ஓர் அன்பான அழைப்பு — விஷமற்ற உணவைத் தேர்ந்தெடுக்க, இயற்கை மண் தரும் நன்மையை மதிக்க, வரும் தலைமுறைக்கு ஆரோக்கியமான உலகை விட்டுச்செல்ல.',
 tocKick:'உள்ளடக்கம்', tocTitle:'இந்த நூலில்', tocFoot:'ஐந்து சிறு அத்தியாயங்கள். வரிசையாகப் படியுங்கள், அல்லது தேவையான பக்கத்திற்கு நேராகச் செல்லுங்கள்.',
 toc:[{n:'1',t:'விஷமற்ற உணவின் முக்கியத்துவம்',p:'04',go:3},{n:'2',t:'இயற்கை உணவின் மதிப்பு',p:'07',go:6},{n:'3',t:'வரும் தலைமுறைக்காக',p:'10',go:9},{n:'4',t:'இயற்கை மூலிகைகள்',p:'13',go:12},{n:'5',t:'தானியம், மாவு, உலர் பழங்கள்',p:'33',go:32}],
 c1Label:'அத்தியாயம் ஒன்று', c1Title:'விஷமற்ற உணவின்<br>முக்கியத்துவம்', c1Sub:'நாம் உண்பதே நாம் ஆகிறோம்',
 c1H:'நாம் உண்பதே நாம் ஆகிறோம்', c1Lead:'வணிக விவசாயத்தில் பரவலாகப் பயன்படுத்தப்படும் பூச்சிக்கொல்லிகளும் இரசாயன உரங்களும் அறுவடையுடன் நமது உடலிலும் நுழைகின்றன.', c1P2:'சிறிய அளவில் இருந்தாலும், நீண்ட காலமாக உடலில் சேரும்போது இந்த இரசாயனங்கள் செரிமானம், ஹார்மோன் சமநிலை, நோய் எதிர்ப்பு சக்தி ஆகியவற்றைப் பாதிக்கலாம் என ஆய்வுகள் காட்டுகின்றன.', c1P3:'விஷமற்ற உணவைத் தேர்ந்தெடுப்பது என்பது அந்தத் தேவையற்ற சுமையை உடலிலிருந்து நீக்குவதாகும். நோயைக் குணப்படுத்துவதை விட, நோய் வராமல் தடுப்பதற்கான முதலீடு இது.',
 q1Kick:'நினைவில் கொள்ளுங்கள்', q1Quote:'“உணவே உன் மருந்தாகட்டும் — மருந்தே உன் உணவாகட்டும்.”', q1Sub:'நாள் ஒன்றுக்கு மூன்று முறை நீங்கள் செய்யும் தேர்வே உங்களிடமுள்ள எளிய பாதுகாப்பு.',
 c2Label:'அத்தியாயம் இரண்டு', c2Title:'இயற்கை உணவின்<br>மதிப்பு', c2Sub:'உயிருள்ள மண்ணின் கொடை',
 c2H:'உயிருள்ள மண்ணின் கொடை', c2Lead:'இயற்கை விளைச்சலின் மதிப்பு மண்ணிலேயே தொடங்குகிறது. உயிருள்ள, ஊட்டமிக்க மண்ணில் வளரும் தாவரம் அதிக ஊட்டச்சத்தைச் சுமந்து வருகிறது.', c2P2:'இரசாயனமற்ற உரமும் இயற்கை முறைகளும் கொண்டு பேணப்பட்ட மண்ணில் நுண்ணுயிரிகளும் ஊட்டச்சத்துகளும் நிறைந்துள்ளன. இது காய்கறிகளுக்கும் பழங்களுக்கும் இயற்கையான சுவை, மணம், நீண்ட நாள் நிலைத்திருக்கும் தன்மையைத் தருகிறது.', c2P3:'மேலும் இயற்கை விவசாயம் நீர், மண், உயிர்ப்பன்மையைப் பாதுகாக்கிறது — அதாவது நாம் செய்யும் ஒவ்வொரு தேர்வும் சுற்றுச்சூழலுக்கும் ஒரு கொடையே.',
 c2ImgKick:'புத்தம்புது', c2ImgTitle:'சுவையும் அதிகம், நலமும் அதிகம்.',
 c3Label:'அத்தியாயம் மூன்று', c3Title:'வரும்<br>தலைமுறைக்காக', c3Sub:'நாம் விட்டுச்செல்லும் உலகம்',
 c3H:'நாம் விட்டுச்செல்லும் உலகம்', c3Lead:'நாம் நம் குழந்தைகளுக்குப் பணத்தையோ சொத்தையோ மட்டும் விட்டுச்செல்வதில்லை — ஒரு மண்ணையும், நீரையும், உணவுப் பண்பாட்டையும் விட்டுச்செல்கிறோம்.', c3P2:'குழந்தைகளுக்கு நல்ல உணவு ஏன் கொடுக்க வேண்டும்? ஏனெனில் அவர்களின் வளர்ச்சி, மூளையின் செயல்பாடு, எதிர்கால ஆரோக்கியம் அனைத்தும் இன்று அவர்கள் உண்ணும் உணவின் மேலேயே கட்டமைக்கப்படுகின்றன.', c3P3:'இரசாயனத்தை நம்பாத, இயற்கையை மதிக்கும் விவசாய முறையைப் பின்பற்றுவது என்பது — நம் குழந்தைகளையும் அவர்களின் குழந்தைகளையும் ஊட்டக்கூடிய மண்ணை நிலையாகப் பாதுகாப்பதாகும்.',
 c3StepKick:'சிறு அடிகள்', c3StepTitle:'இன்றே செய்யக்கூடியவை', c3StepFoot:'மாற்றம் பெரிதாக இருக்க வேண்டியதில்லை. அது தொடங்கினால் போதும்.',
 c3Steps:[{t:'① இயற்கையைத் தேர்ந்தெடுங்கள்',b:'வாரம் ஒரு வேளையாவது இரசாயனமற்ற காய்கறிகளுக்கு மாறுங்கள்.'},{t:'② உள்ளூரில் வாங்குங்கள்',b:'அருகிலுள்ள விவசாயியிடமோ நம்பகமான கடையிலோ வாங்குவது புத்துணர்வையும் தரத்தையும் காக்கும்.'},{t:'③ சிறிதாக விளைவியுங்கள்',b:'வீட்டு மூலையில் கறிவேப்பிலை, வல்லாரை நடுவதிலிருந்து தொடங்குங்கள்.'}],
 c4Label:'அத்தியாயம் நான்கு', c4Title:'இயற்கை<br>மூலிகைகள்', c4Sub:'இயற்கையின் மருந்து', c4Blurb:'இயற்கை நமக்குத் தந்த சில மூலிகைகள் — அவற்றின் நலன்களும், பயன்படுத்தும் முறையும் இங்கிருந்து.',
 c5Label:'அத்தியாயம் ஐந்து', c5Title:'தானியம், மாவு,<br>உலர் பழங்கள்', c5Sub:'அன்றாட ஊட்டம்', c5Blurb:'அன்றாட உணவில் சேர்க்கக்கூடிய ஊட்டமிக்க தானியங்கள், மாவு வகைகள், இயற்கை சிற்றுண்டிகள்.',
 itemHerbCat:'மூலிகை', itemFoodCat:'முழு உணவு', labBenefit:'உடலுக்கான மதிப்பு', labUse:'பயன்படுத்தும் முறை', labTip:'தெரிந்துகொள்ளுங்கள்', photoPh:'படம்',
 closeKick:'Kenko 1st Organic', closeTitle:'இயற்கையின் நலம்,<br>உங்கள் மேசைக்கு', closeTagline:'Live a healthy life · Think next generation', closeBlurb:'சுத்தமான, விஷமற்ற இயற்கைப் பொருட்களுக்கு எங்களை நாடுங்கள். ஒவ்வொரு பொருளும் இயற்கையையும் உங்கள் குடும்பத்தையும் மதித்துத் தேர்ந்தெடுக்கப்பட்டது.',
 contact:['முகவரி · Address','தொலைபேசி · Phone','இணையம் · Web'],
 hint:'பக்கத்தின் இருபுறமும் அழுத்துங்கள் · ← → · பக்கம் புரட்ட',
 herbs:[
  {name:'நெல்லிக்காய் (ஆம்லா)',b:'உலகிலேயே வைட்டமின் C அதிகம் உள்ள உணவுகளில் நெல்லி முன்னணியில் உள்ளது. இது நோய் எதிர்ப்பு சக்தியை வலுப்படுத்தி, செரிமானத்திற்கு உதவும்; ஆன்டிஆக்சிடன்ட் நிறைந்ததால் தோலையும் முடியையும் ஆரோக்கியமாக வைக்கிறது.',u:'ஒரு தேக்கரண்டியை வெந்நீர் அல்லது தேனுடன் கலந்து காலையில் வெறும் வயிற்றில் எடுத்துக்கொள்ளுங்கள்; ஸ்மூத்தி, பழச்சாறுகளிலும் சேர்க்கலாம்.',t:['நோய் எதிர்ப்பு','வைட்டமின் C','தோல் & முடி'],k:'தினமும் ஒரு தேக்கரண்டி வழக்கமாக எடுப்பது சிறந்த பலனளிக்கும்.'},
  {name:'அஸ்வகந்தா',b:'மன அழுத்தத்தையும் சோர்வையும் குறைக்கும் "அடாப்டோஜென்" மூலிகை. சக்தி, நல்ல தூக்கம், கவனம் ஆகியவற்றை மேம்படுத்தி உடலின் இயற்கை எதிர்ப்பாற்றலைக் கட்டியெழுப்புகிறது.',u:'இரவு உறங்குமுன் ஒரு டம்ளர் சூடான பாலில் அரை தேக்கரண்டி கலந்து அருந்துங்கள்.',t:['அழுத்தம் குறைவு','சக்தி','நல்ல தூக்கம்'],k:'சில வாரங்கள் தொடர்ந்து எடுப்பது மன அழுத்த மேலாண்மைக்கு உதவும்.'},
  {name:'ஹீன்போவிட்டிய',b:'இரத்த சர்க்கரையைக் கட்டுப்படுத்தவும் உடலிலுள்ள விஷத்தை நீக்கவும் பாரம்பரிய மருத்துவத்தில் பரவலாகப் பயன்படுகிறது. தோல் பிரச்சினைகளுக்கும் நல்லது.',u:'ஒரு தேக்கரண்டியை வெந்நீரில் கலந்து கஷாயமாக அருந்துங்கள்.',t:['இரத்த சர்க்கரை','உடல் சுத்திகரிப்பு','தோல்'],k:'நீரிழிவு உள்ளவர்கள் மருத்துவ ஆலோசனையுடன் பயன்படுத்துவது நல்லது.'},
  {name:'கடுபில',b:'உடலிலுள்ள விஷத்தை நீக்கவும் சிறுநீரக ஆரோக்கியத்திற்கும் பாரம்பரிய மருத்துவத்தில் மதிக்கப்படும் மூலிகை. இரத்த சர்க்கரைக் கட்டுப்பாட்டிற்கும் பயன்படுகிறது.',u:'கஷாயமாகத் தயாரித்து பரிந்துரைக்கப்பட்ட அளவில் எடுத்துக்கொள்ளுங்கள்.',t:['விஷ நீக்கம்','சிறுநீரகம்','இரத்த சர்க்கரை'],k:'பாரம்பரியமாக மதிக்கப்படும் நாட்டு மூலிகை.'},
  {name:'லுணுவில (பகோபா)',b:'நினைவாற்றல், கவனம், மூளை செயல்பாட்டை மேம்படுத்த உலகெங்கும் பிரபலமான மூலிகை. நரம்புகளை அமைதிப்படுத்தி மன அழுத்தத்தைக் குறைக்கிறது.',u:'தேன் அல்லது பாலுடன் ஒரு தேக்கரண்டி எடுத்துக்கொள்ளுங்கள்; பள்ளி வயது குழந்தைகளுக்கும் ஏற்றது.',t:['நினைவாற்றல்','மூளை','நரம்பு'],k:'படிக்கும் குழந்தைகளுக்கு உகந்த பாரம்பரிய மூலிகை.'},
  {name:'துளசி',b:'இருமல், சளி, மூச்சுத் தொல்லைகளைத் தணிக்கும் புனிதத் தாவரம். நோய் எதிர்ப்பு சக்தியை மேம்படுத்தி மன அழுத்தத்தையும் குறைக்கிறது.',u:'வெந்நீரில் ஊறவைத்து துளசி டீயாக அருந்துங்கள்; விரும்பினால் தேன் சேர்க்கலாம்.',t:['இருமல்/சளி','நோய் எதிர்ப்பு','மூச்சு'],k:'காலையில் ஒரு கோப்பை மென்மையான ஆறுதல் தரும்.'},
  {name:'யகினாரன்',b:'காய்ச்சல், இருமல், இரத்த சுத்திகரிப்புக்குப் பாரம்பரியமாகப் பயன்படும் மூலிகை. உடலைக் குளிர்விக்கும் குணம் கொண்டது.',u:'கஷாயமாகத் தயாரித்து அருந்துங்கள்.',t:['காய்ச்சல்','இரத்த சுத்திகரிப்பு','குளிர்ச்சி'],k:'நாட்டு மருத்துவத்தின் பழமையான மூலிகை.'},
  {name:'கொத்தல ஹிம்புட்டு',b:'இரத்த சர்க்கரை, எடை மேலாண்மைக்கு உலகெங்கும் அறியப்பட்ட பாரம்பரிய மூலிகை. சர்க்கரை உறிஞ்சுதலைத் தாமதப்படுத்தும் எனக் கருதப்படுகிறது.',u:'வெந்நீரில் கரைத்து உணவுக்கு முன் எடுத்துக்கொள்ளுங்கள்.',t:['இரத்த சர்க்கரை','எடை','நீரிழிவு'],k:'உணவுக்கு 30 நிமிடங்களுக்கு முன் எடுப்பது சிறந்தது.'},
  {name:'நீரமுல்லிய',b:'சிறுநீர் அமைப்பு, சிறுநீரகம், கல்லீரல் ஆரோக்கியத்திற்கு நல்லது. உடலிலுள்ள தேவையற்ற நீரை வெளியேற்ற உதவுகிறது.',u:'கஷாயமாகத் தயாரித்து அருந்துங்கள்.',t:['சிறுநீரகம்','சிறுநீர்','கல்லீரல்'],k:'அதிகம் நீர் அருந்தியபடி பயன்படுத்துங்கள்.'},
  {name:'பப்பாளி இலை',b:'இரத்த தட்டணுக்கள் (platelets) அதிகரிப்புக்கும் செரிமானத்திற்கும் நல்லது எனப் பாரம்பரியமாக நம்பப்படுகிறது. டெங்கு குணமாகும் நேரத்திலும் பரவலாகப் பயன்படுகிறது.',u:'ஒரு டம்ளர் நீரில் சிறிதளவு கலந்து எடுத்துக்கொள்ளுங்கள்; சாறாகவும் அருந்தலாம்.',t:['தட்டணுக்கள்','செரிமானம்','டெங்கு'],k:'கடுமையான நோய் நிலைகளில் மருத்துவ ஆலோசனை பெறுங்கள்.'},
  {name:'ரணவரா மலர்',b:'இரத்த சர்க்கரையையும் தோல் தூய்மையையும் ஆதரிக்கும், காஃபின் இல்லாத டீ மாற்று மலர். உடலைக் குளிர்விக்கிறது.',u:'வெந்நீரில் ஊறவைத்து ரணவரா டீயாக அருந்துங்கள்.',t:['இரத்த சர்க்கரை','தோல்','டீ மாற்று'],k:'காலையில் காஃபின் இல்லாத அருமையான பானம்.'},
  {name:'ரசகிந்த (குடூச்சி)',b:'நோய் எதிர்ப்பு, காய்ச்சல், மூட்டு ஆரோக்கியத்திற்கு ஆயுர்வேதத்தில் "அமிர்தம்" என அழைக்கப்படும் மூலிகை. உடலின் எதிர்ப்பாற்றலைக் கட்டியெழுப்புகிறது.',u:'கஷாயமாகத் தயாரித்து அருந்துங்கள்.',t:['நோய் எதிர்ப்பு','காய்ச்சல்','மூட்டு'],k:'ஆயுர்வேதத்தில் "குடூச்சி" எனப் பிரபலம்.'},
  {name:'சீதா இலை',b:'ஆன்டிஆக்சிடன்ட் நிறைந்தது; தூக்கத்திற்கும் நோய் எதிர்ப்பு சக்திக்கும் நல்லது எனக் கருதப்படுகிறது. உடலை அமைதிப்படுத்துகிறது.',u:'இலைகளை வெந்நீரில் கொதிக்கவைத்து இரவில் டீயாக அருந்துங்கள்.',t:['ஆன்டிஆக்சிடன்ட்','தூக்கம்','நோய் எதிர்ப்பு'],k:'இரவு நேர ஆறுதல் தரும் டீ.'},
  {name:'தேபு',b:'இரத்த சர்க்கரையையும் கொலஸ்ட்ராலையும் ஆதரிக்கும் பாரம்பரிய மூலிகை. நீரிழிவு மேலாண்மையில் பரவலாகப் பயன்படுகிறது.',u:'உணவில் சேர்த்து அல்லது நீருடன் எடுத்துக்கொள்ளுங்கள்; பசுமையான இலைகளை சாலட்டாகவும் உண்ணலாம்.',t:['இரத்த சர்க்கரை','கொலஸ்ட்ரால்','நீரிழிவு'],k:'"நீரிழிவு தாவரம்" எனப் பிரபலம்.'},
  {name:'பொல்பல',b:'சிறுநீரகக் கல், சிறுநீர் தொல்லைகளைத் தணிக்கவும் உடலைக் குளிர்விக்கவும் பாரம்பரியமாகப் பயன்படுகிறது. உடலின் தேவையற்ற வெப்பத்தைக் குறைக்கிறது.',u:'கஷாயமாக அல்லது பொல்பல கஞ்சியாகத் தயாரித்து எடுத்துக்கொள்ளுங்கள்.',t:['சிறுநீரகம்','சிறுநீர்','குளிர்ச்சி'],k:'பொல்பல கஞ்சி பாரம்பரிய நலவுணவு.'},
  {name:'இலங்கை இலவங்கப்பட்டை',b:'இரத்த சர்க்கரை சமநிலைக்கு நல்ல, ஆன்டிஆக்சிடன்ட் நிறைந்த மணமிக்க வாசனைப்பொருள். இலங்கையின் "உண்மை இலவங்கம்" உலகின் சிறந்ததாகக் கருதப்படுகிறது.',u:'டீ, பால் அல்லது சமையலில் சேர்க்கவும்; கேக், புட்டிங்கிலும் அருமை.',t:['இரத்த சர்க்கரை','மணம்','ஆன்டிஆக்சிடன்ட்'],k:'Ceylon Cinnamon உலகம் மதிக்கும் நாட்டுப் பொருள்.'},
  {name:'இஞ்சி',b:'செரிமானத்திற்கு உதவும், குமட்டல், சளியைத் தணிக்கும் அழற்சி எதிர்ப்பு வாசனைப்பொருள். உடலைச் சூடாக்குகிறது.',u:'டீ, சமையல் அல்லது வெந்நீரில் கலந்து எடுத்துக்கொள்ளுங்கள்.',t:['செரிமானம்','அழற்சி எதிர்ப்பு','சளி'],k:'குளிர் நாட்களுக்கு இஞ்சி டீ ஏற்றது.'},
  {name:'முருங்கை',b:'வைட்டமின், இரும்பு, கால்சியம், புரதம், ஆன்டிஆக்சிடன்ட் நிறைந்த ஊட்டமிக்க "சூப்பர்ஃபுட்". சக்தியையும் நோய் எதிர்ப்பு சக்தியையும் மேம்படுத்துகிறது.',u:'சூப், கறி, கஞ்சி அல்லது ஸ்மூத்தியில் ஒரு தேக்கரண்டி சேர்க்கவும்.',t:['ஊட்டம்','இரும்பு','புரதம்'],k:'"அற்புத மரம்" என உலகெங்கும் பிரபலம்.'},
  {name:'இரமுசு',b:'உடலைக் குளிர்விக்கும், இரத்தத்தைச் சுத்திகரிக்கும், தோல் ஆரோக்கியத்திற்கு நல்ல மணமிக்க வேர். தாகத்தைத் தணிக்கிறது.',u:'வெந்நீர் அல்லது குளிர்ந்த நீரில் கலந்து புத்துணர்ச்சி பானமாக அருந்துங்கள்.',t:['குளிர்ச்சி','இரத்த சுத்திகரிப்பு','தோல்'],k:'சூடான நாட்களுக்கு இரமுசு பானம் புத்துணர்ச்சி.'},
 ],
 foods:[
  {name:'கேழ்வரகு மாவு',b:'கால்சியம், இரும்பு, நார்ச்சத்து நிறைந்த குறைந்த GI தானிய மாவு. நீரிழிவுக்கு நல்லது; குழந்தைகளின் எலும்பு வளர்ச்சிக்கும் உதவும்.',u:'ரொட்டி, புட்டு, கஞ்சி, தலப்பா அல்லது பான்கேக்காகச் செய்யுங்கள்.',t:['கால்சியம்','நார்ச்சத்து','குறைந்த GI'],k:'காலை கேழ்வரகு கஞ்சி சக்தி தரும் உணவு.'},
  {name:'கிதுல் மாவு',b:'சக்தி தரும் பாரம்பரிய குறைந்த GI இயற்கை மாவு. உடலைக் குளிர்விக்கும் குணம் உள்ளதாக நம்பப்படுகிறது.',u:'தலப்பா, கஞ்சி அல்லது இனிப்பு உணவாகச் செய்யுங்கள்.',t:['சக்தி','குறைந்த GI','பாரம்பரியம்'],k:'கிதுல் தலப்பா விரும்பப்படும் நாட்டு உணவு.'},
  {name:'பச்சைப் பயறு',b:'எளிதில் ஜீரணமாகும், புரதமும் சக்தியும் நிறைந்த தானியம். வயிற்றுக்கு இலகுவானது, உடலைக் குளிர்விக்கும்.',u:'வேகவைத்து, கஞ்சியாக அல்லது இனிப்புகளில் பயன்படுத்துங்கள்.',t:['புரதம்','இலகு','சக்தி'],k:'வேகவைத்த பயறு காலை உணவுக்கு அருமை.'},
  {name:'சிவப்பு காராமணி',b:'புரதம், நார்ச்சத்து, இரும்பு நிறைந்த வயிறு நிறைக்கும் தானியம். நீண்ட நேரம் பசியைத் தடுக்கும்.',u:'தேங்காயுடன் வேகவைத்து காலை உணவாக அல்லது கறியாக எடுத்துக்கொள்ளுங்கள்.',t:['புரதம்','இரும்பு','நார்ச்சத்து'],k:'சக்தி தரும் காலை உணவு.'},
  {name:'வெள்ளை காராமணி',b:'புரதமும் நார்ச்சத்தும் நிறைந்த நலவுணவுத் தானியம். சர்க்கரையை மெதுவாக வெளியிட்டு நீடித்த சக்தி தருகிறது.',u:'தேங்காயுடன் வேகவைத்து காலை உணவாக எடுத்துக்கொள்ளுங்கள்.',t:['புரதம்','நார்ச்சத்து','நீடித்த சக்தி'],k:'தேங்காயுடன் வேகவைப்பது சுவையானது.'},
  {name:'சுவந்தல் அரிசி',b:'மணமும் ஊட்டமும் நிறைந்த பாரம்பரிய நாட்டு அரிசி. தனித்துவமான மணமும் சுவையும் கொண்டது.',u:'சாதம், பால் சாதம் அல்லது சிறப்பு விழா உணவாகச் சமையுங்கள்.',t:['மணம்','நாட்டு','ஊட்டம்'],k:'விழா நாட்களுக்கான சிறப்பு அரிசி.'},
  {name:'தேன்',b:'சர்க்கரைக்குப் பதிலாகப் பயன்படுத்தக்கூடிய இயற்கை இனிப்பு. தொண்டை தொல்லை, இருமலைத் தணிக்கும், நோய் எதிர்ப்பு சக்திக்கும் நல்லது.',u:'வெந்நீர், டீ, பழம் அல்லது உணவில் சர்க்கரைக்குப் பதிலாகச் சேர்க்கவும்.',t:['இயற்கை இனிப்பு','தொண்டை','நோய் எதிர்ப்பு'],k:'வெந்நீருடன் தேன் அருமையான காலை பானம்.'},
  {name:'கிதுல் பாகு',b:'தாதுக்கள் நிறைந்த குறைந்த GI இயற்கை இனிப்பு. சுத்திகரிக்கப்பட்ட சர்க்கரையை விட ஆரோக்கியமானது.',u:'ஆப்பம், தயிர், பழத்தின் மேல் ஊற்றி அல்லது சர்க்கரைக்குப் பதிலாகப் பயன்படுத்துங்கள்.',t:['குறைந்த GI','தாதுக்கள்','இயற்கை'],k:'ஆப்பம், தயிருடன் விரும்பப்படும் நாட்டுச் சுவை.'},
  {name:'அவல்',b:'எளிதில் சக்தி தரும், விரைவில் ஜீரணமாகும் இலகுவான உணவு. பரபரப்பான காலைகளுக்கு ஏற்றது.',u:'பால், தயிர், தேங்காய் அல்லது தேனுடன் கலந்து எடுத்துக்கொள்ளுங்கள்.',t:['விரைவு சக்தி','இலகு','எளிது'],k:'சில நிமிடங்களில் தயாராகும் உணவு.'},
  {name:'உலர் மாம்பழம்',b:'வைட்டமின், நார்ச்சத்து, ஆன்டிஆக்சிடன்ட் நிறைந்த, சர்க்கரை சேர்க்காத இயற்கை சிற்றுண்டி. பதப்படுத்திய தின்பண்டங்களுக்கு ஆரோக்கிய மாற்று.',u:'நேரடியாகச் சிற்றுண்டியாக சுவையுங்கள்; தானியம் அல்லது தயிரிலும் சேர்க்கலாம்.',t:['சர்க்கரையின்றி','வைட்டமின்','சிற்றுண்டி'],k:'குழந்தைகளின் மதிய உணவுப் பெட்டிக்கு ஆரோக்கியம்.'},
  {name:'உலர் அன்னாசி',b:'வைட்டமின் C, ஜீரண நொதிகள் நிறைந்த இயற்கை சிற்றுண்டி. செயற்கைச் சேர்க்கை இல்லாதது.',u:'நேரடியாகச் சிற்றுண்டியாக எடுத்துக்கொள்ளுங்கள்.',t:['வைட்டமின் C','செரிமானம்','சிற்றுண்டி'],k:'சுவையான இயற்கை இனிப்பு.'},
  {name:'உலர் வாழைப்பழம்',b:'பொட்டாசியமும் சக்தியும் நிறைந்த இயற்கை சிற்றுண்டி. உடற்பயிற்சிக்குப் பின் சக்தி பெற ஏற்றது.',u:'நேரடியாக அல்லது தானியத்துடன் கலந்து எடுத்துக்கொள்ளுங்கள்.',t:['பொட்டாசியம்','சக்தி','சிற்றுண்டி'],k:'விளையாட்டு வீரர்களுக்கு இயற்கை சக்தி உணவு.'},
  {name:'உலர் பலாச்சுளை',b:'பழுத்த பலாச்சுளைகள், இரசாயனமோ சேர்க்கப்பட்ட சீனியோ இன்றி வெயிலில் அல்லது குறைந்த வெப்பத்தில் உலர்த்தப்பட்டவை. நார்ச்சத்து, பொட்டாசியம், இயற்கை சக்தி நிறைந்தது; ஜீரணத்திற்கு இதமானது. பலா பருவத்தின் சுவையை ஆண்டு முழுவதும் தருகிறது.',u:'சிற்றுண்டியாக அப்படியே உண்ணுங்கள், அல்லது பால், தானியம், இனிப்புகளுடன் சேர்க்கலாம். உலர்ந்த, காற்றுப்புகாத ஜாடியில் வைக்கவும்.',t:['நார்ச்சத்து','இயற்கை சக்தி','சிற்றுண்டி'],k:'இலங்கையில் "சோற்று மரம்" என அழைக்கப்படும் பலா மரத்தின் பழுத்த கனியிலிருந்து தயாரிக்கப்படுகிறது.'},
 ],
};

BOOK.ja={
 guide:'すこやかに暮らすための小さな本', coverTitle:'土から食卓へ', coverSub:'毒のない、オーガニックな暮らしのために', coverBlurb:'清らかな食べもの、有機作物の価値、自然のハーブがもたらす癒やしについての小さな本。',
 fwKick:'まえがき', fwTitle:'小さな選択が、大きな違いに', fwLead:'私たちが毎日えらぶ食べものは、健康と土と、次の世代をかたちづくります。これはその選択について、やさしく正直に語る小さな本です。', fwP2:'化学肥料や農薬を使わずに育てられた食べものの価値、自然のハーブがもつ癒やし、そしてそれらを日々の暮らしに取り入れる方法を紹介します。', fwP3:'これはひとつの招きです——毒のない食べものをえらび、有機の土が与えてくれるものを大切にし、次の世代により健やかな世界を手わたすために。',
 tocKick:'もくじ', tocTitle:'この本のなかみ', tocFoot:'短い章が五つ。順に読んでも、必要なところへ直接めくっても。',
 toc:[{n:'1',t:'毒のない食べものが大切な理由',p:'04',go:3},{n:'2',t:'有機の食べものの価値',p:'07',go:6},{n:'3',t:'次の世代のために',p:'10',go:9},{n:'4',t:'自然のハーブ',p:'13',go:12},{n:'5',t:'穀物・粉・ドライフルーツ',p:'33',go:32}],
 c1Label:'第一章', c1Title:'毒のない食べものが<br>大切な理由', c1Sub:'私たちは食べたものになる',
 c1H:'私たちは食べたものになる', c1Lead:'商業的な農業で広く使われる農薬や化学肥料は、収穫物とともに私たちの体にも入ってきます。', c1P2:'たとえ少量でも、長い時間をかけて体に取り込まれると、これらの化学物質は消化やホルモンのバランス、免疫の働きに影響しうると研究は示しています。', c1P3:'毒のない食べものをえらぶことは、その不要な負担を体から取りのぞくことです。病気を治すためというより、病気を招き入れないための投資なのです。',
 q1Kick:'心にとめて', q1Quote:'「食を汝の薬とし、薬を汝の食とせよ。」', q1Sub:'一日に三度おこなうその選択こそ、あなたがもついちばんかんたんな守りです。',
 c2Label:'第二章', c2Title:'有機の<br>食べものの価値', c2Sub:'生きた土からの贈りもの',
 c2H:'生きた土からの贈りもの', c2Lead:'有機作物の価値は土からはじまります。生きた、栄養ゆたかな土で育つ植物は、より多くの栄養をたずさえてきます。', c2P2:'化学肥料を使わず自然の方法で育まれた土は、微生物と栄養にみちています。それが野菜や果物に、自然な味と香り、そして日もちのよさを与えます。', c2P3:'さらに有機農業は水と土と生物多様性を守ります——つまり私たちのえらぶひとつひとつが、環境への贈りものでもあるのです。',
 c2ImgKick:'みずみずしく', c2ImgTitle:'味も、よさも、どちらもゆたかに。',
 c3Label:'第三章', c3Title:'次の世代の<br>ために', c3Sub:'私たちが残す世界',
 c3H:'私たちが残す世界', c3Lead:'私たちが子どもたちに残すのはお金や財産だけではありません——土と、水と、食の文化をも残すのです。', c3P2:'なぜ子どもたちによい食べものを与えるべきなのでしょう。それは、彼らの成長も、脳の働きも、これからの健康も、今日食べるものの上に築かれるからです。', c3P3:'化学物質に頼らず、自然を敬う農のあり方にならうこと——それは、私たちの子にも、その子にも実りをもたらす土を、末永く守ることです。',
 c3StepKick:'小さな一歩', c3StepTitle:'今日できること', c3StepFoot:'変化は大きくなくてよいのです。ただ、はじまることが大切です。',
 c3Steps:[{t:'① 有機をえらぶ',b:'週に一度の食事だけでも、化学物質を使わない野菜に切りかえてみましょう。'},{t:'② 地元で買う',b:'近くの農家や信頼できるお店で買うことが、みずみずしさと質を守ります。'},{t:'③ 少し育てる',b:'庭のすみでカレーリーフやツボクサを育てることからはじめましょう。'}],
 c4Label:'第四章', c4Title:'自然の<br>ハーブ', c4Sub:'自然の薬', c4Blurb:'自然が私たちに与えてくれたハーブをいくつか——その効きめと使い方を、ここから。',
 c5Label:'第五章', c5Title:'穀物・粉・<br>ドライフルーツ', c5Sub:'毎日の栄養', c5Blurb:'日々の食事に取り入れられる、栄養ゆたかな穀物や粉、自然のおやつ。',
 itemHerbCat:'ハーブ', itemFoodCat:'全粒食品', labBenefit:'体へのめぐみ', labUse:'使い方', labTip:'知っておくと', photoPh:'画像',
 closeKick:'Kenko 1st Organic', closeTitle:'自然のめぐみを、<br>あなたの食卓へ', closeTagline:'Live a healthy life · Think next generation', closeBlurb:'清らかで毒のない、有機の品々は私たちへ。どの品も、自然とあなたの家族を敬いながらえらばれています。',
 contact:['ご住所 · Address','お電話 · Phone','ウェブ · Web'],
 hint:'ページの両端をクリック · ← → キー · でめくれます',
 herbs:[
  {name:'アムラ（インドスグリ）',b:'アムラは世界でもっともビタミンCが豊富な食べもののひとつです。免疫を高め消化を助け、抗酸化物質にとみ、肌と髪を健やかに保ちます。',u:'小さじ一杯を白湯かはちみつに混ぜ、毎朝空腹時にどうぞ。スムージーや果汁にもよく合います。',t:['免疫','ビタミンC','髪と肌'],k:'毎日小さじ一杯を続けると、よい結果が得られます。'},
  {name:'アシュワガンダ',b:'ストレスと疲れをやわらげる「アダプトゲン」のハーブです。活力・よい眠り・集中を支え、体の自然な回復力を育てます。',u:'夜、寝る前に温めた牛乳一杯に小さじ半分を混ぜてお飲みください。',t:['ストレス軽減','活力','よい眠り'],k:'数週間つづけると、ストレスの管理に役立ちます。'},
  {name:'ヒーンボーウィティヤ',b:'血糖の管理と体内の毒素を出すために、伝統医学で広く使われてきました。肌の悩みにもよいとされます。',u:'小さじ一杯を白湯に溶かし、煎じ薬としてお飲みください。',t:['血糖','体の浄化','肌'],k:'糖尿病の方は医師の助言とともにお使いください。'},
  {name:'カトゥピラ',b:'体内の解毒と腎臓の健康のために、伝統医学で重んじられるハーブです。血糖の管理にも用いられます。',u:'煎じ薬にして、すすめられた量をお飲みください。',t:['解毒','腎臓','血糖'],k:'古くから大切にされてきた民間のハーブです。'},
  {name:'ルヌウィラ（バコパ）',b:'記憶・集中・脳の働きを支えることで世界に知られるハーブです。神経をしずめ、ストレスをやわらげます。',u:'はちみつか牛乳とともに小さじ一杯を。学齢期のお子さんにも向きます。',t:['記憶','脳','神経'],k:'学ぶ子どもに向く伝統のハーブです。'},
  {name:'トゥルシー（ホーリーバジル）',b:'せき・かぜ・呼吸の不調をやわらげる神聖な植物です。免疫を高め、ストレスもやわらげます。',u:'白湯に浸してトゥルシーティーとして。お好みではちみつを加えても。',t:['せき/かぜ','免疫','呼吸'],k:'朝の一杯は、やさしい癒やしのひとときに。'},
  {name:'ヤキナラン',b:'熱・せき・血の浄化のために伝統的に用いられるハーブです。体を冷やす性質があります。',u:'煎じ薬にしてお飲みください。',t:['熱','血の浄化','冷やす'],k:'民間医学の古いハーブです。'},
  {name:'コッタラヒンブトゥ',b:'血糖と体重の管理で世界に知られる伝統のハーブです。糖の吸収をゆるやかにするとされます。',u:'白湯に溶かして食前にどうぞ。',t:['血糖','体重','糖尿病'],k:'食事の30分ほど前にとるのがおすすめです。'},
  {name:'ニーラムッリヤ',b:'泌尿器・腎臓・肝臓の健康によいハーブです。体の余分な水分を出すのを助けます。',u:'煎じ薬にしてお飲みください。',t:['腎臓','泌尿器','肝臓'],k:'水をよく飲みながらお使いください。'},
  {name:'パパイヤの葉',b:'血小板の維持と消化によいと、伝統的に信じられています。デング熱の回復期にも広く用いられます。',u:'コップ一杯の水に少量を混ぜて。果汁としてもどうぞ。',t:['血小板','消化','デング熱'],k:'重い症状のときは医師の助言をお受けください。'},
  {name:'ラナワラの花',b:'血糖と澄んだ肌を支える、カフェインのないお茶がわりの花です。体を冷やします。',u:'白湯に浸してラナワラティーとしてお飲みください。',t:['血糖','肌','お茶がわり'],k:'カフェインのない、すてきな朝の飲みものです。'},
  {name:'ラサキンダ（グドゥチ）',b:'免疫・熱・関節の健康のため、アーユルヴェーダで「甘露」と呼ばれるハーブです。体の抵抗力を育てます。',u:'煎じ薬にしてお飲みください。',t:['免疫','熱','関節'],k:'アーユルヴェーダでは「グドゥチ」として知られます。'},
  {name:'サワーソップの葉',b:'抗酸化物質にとみ、眠りと免疫によいとされます。体をしずめます。',u:'葉を白湯で煮出し、夜にお茶としてどうぞ。',t:['抗酸化','眠り','免疫'],k:'夜のやすらぎのお茶に。'},
  {name:'テブ',b:'血糖とコレステロールを支える伝統のハーブです。糖尿病の管理に広く用いられます。',u:'料理に加えるか水とともに。生の葉はサラダでも。',t:['血糖','コレステロール','糖尿病'],k:'「糖尿病の植物」として親しまれます。'},
  {name:'ポルパラ',b:'腎臓結石や泌尿の不調をやわらげ、体を冷やすために伝統的に用いられます。体内の余分な熱をしずめます。',u:'煎じ薬として、またはポルパラのおかゆにしてどうぞ。',t:['腎臓','泌尿','冷やす'],k:'ポルパラのおかゆは伝統の癒やし食です。'},
  {name:'セイロンシナモン',b:'血糖のバランスによい、抗酸化物質ゆたかな香り高いスパイスです。スリランカの「真のシナモン」は世界一とされます。',u:'お茶・牛乳・料理に加えて。ケーキやプディングにもよく合います。',t:['血糖','香り','抗酸化'],k:'セイロンシナモンは世界が認める地元の逸品です。'},
  {name:'しょうが',b:'消化を助け、吐きけやかぜをやわらげる抗炎症のスパイスです。体を温めます。',u:'お茶や料理に、または白湯に混ぜてどうぞ。',t:['消化','抗炎症','かぜ'],k:'寒い日にはしょうが湯がぴったりです。'},
  {name:'モリンガ',b:'ビタミン・鉄・カルシウム・たんぱく質・抗酸化物質ゆたかな栄養の「スーパーフード」です。活力と免疫を育てます。',u:'スープ・カレー・おかゆ・スムージーに小さじ一杯を。',t:['栄養','鉄','たんぱく質'],k:'「奇跡の木」として世界に知られます。'},
  {name:'イラムス',b:'体を冷やし、血を浄化し、肌の健康によい香り高い根です。のどのかわきをいやします。',u:'白湯か冷たい水に混ぜ、さわやかな飲みものとしてどうぞ。',t:['冷やす','血の浄化','肌'],k:'暑い日にはイラムスの飲みものがさわやかです。'},
 ],
 foods:[
  {name:'シコクビエ粉（クラカン）',b:'カルシウム・鉄・食物繊維ゆたかな低GIの穀物粉です。糖尿病にやさしく、子どもの骨の成長にも役立ちます。',u:'ロティ・ピットゥ・おかゆ・タラパ・パンケーキに。',t:['カルシウム','食物繊維','低GI'],k:'朝のクラカンがゆは力の出る食事です。'},
  {name:'キトゥル粉',b:'力を与える伝統の低GI自然粉です。体を冷やす性質があるとされます。',u:'タラパ・おかゆ・甘い料理にどうぞ。',t:['活力','低GI','伝統'],k:'キトゥルタラパは親しまれる郷土の一品です。'},
  {name:'緑豆（ムング）',b:'消化がよく、たんぱく質と活力にとむ穀物です。胃にやさしく、体を冷やします。',u:'ゆでて、おかゆに、または甘味にどうぞ。',t:['たんぱく質','軽やか','活力'],k:'ゆで緑豆は朝食にぴったりです。'},
  {name:'赤ささげ',b:'たんぱく質・食物繊維・鉄にとむ、満足感のある穀物です。長くおなかを満たします。',u:'ココナッツとゆでて朝食に、またはカレーに。',t:['たんぱく質','鉄','食物繊維'],k:'力の出る朝の一皿です。'},
  {name:'白ささげ',b:'たんぱく質と食物繊維ゆたかな滋養の穀物です。糖をゆっくり放ち、長もちする活力を与えます。',u:'ココナッツとゆでて朝食にどうぞ。',t:['たんぱく質','食物繊維','持続する活力'],k:'ココナッツとゆでるとおいしくいただけます。'},
  {name:'スワンダル米',b:'香りと栄養ゆたかな伝統の在来米です。きわだつ香りと味わいをもちます。',u:'ごはん・ミルクライス・特別な日の料理に。',t:['香り','在来','栄養'],k:'祝いの日にふさわしい特別なお米です。'},
  {name:'蜂蜜',b:'砂糖のかわりに使える自然の甘味です。のどの不調やせきをやわらげ、免疫にもよいものです。',u:'白湯・お茶・果物・料理に、砂糖のかわりとして。',t:['自然の甘味','のど','免疫'],k:'白湯に蜂蜜は、よい朝の飲みものになります。'},
  {name:'キトゥル糖蜜',b:'ミネラルゆたかな低GIの自然の甘味です。精製糖よりも体にやさしいものです。',u:'ホッパーや凝乳、果物にかけて、または砂糖のかわりに。',t:['低GI','ミネラル','自然'],k:'ホッパーや凝乳と合う郷土の味わいです。'},
  {name:'ライスフレーク',b:'手軽に活力を与え、すぐに消化される軽い食べものです。いそがしい朝にぴったりです。',u:'牛乳・凝乳・ココナッツ・蜂蜜と混ぜてどうぞ。',t:['すばやい活力','軽やか','手軽'],k:'数分で用意できる食べものです。'},
  {name:'ドライマンゴー',b:'ビタミン・食物繊維・抗酸化物質ゆたかで、砂糖不使用の自然のおやつです。加工菓子にかわる健やかな選択です。',u:'そのままおやつに、シリアルやヨーグルトに加えても。',t:['砂糖不使用','ビタミン','おやつ'],k:'子どものお弁当箱にも健やかです。'},
  {name:'ドライパイナップル',b:'ビタミンCと消化酵素にとむ自然のおやつです。人工的なものは加えていません。',u:'そのままおやつとしてどうぞ。',t:['ビタミンC','消化','おやつ'],k:'おいしい自然の甘さです。'},
  {name:'ドライバナナ',b:'カリウムと活力にとむ自然のおやつです。運動のあとの補給にぴったりです。',u:'そのまま、またはシリアルと混ぜてどうぞ。',t:['カリウム','活力','おやつ'],k:'運動する人への自然のエネルギー食です。'},
  {name:'ドライジャックフルーツ',b:'熟したジャックフルーツの果肉を、化学物質や砂糖を加えずに天日または低温で乾燥させました。食物繊維・カリウム・自然の活力にとみ、おなかにやさしい食べものです。旬の味わいを一年中たのしめます。',u:'そのままおやつに、または牛乳・シリアル・デザートに加えてどうぞ。乾燥した密閉びんで保存してください。',t:['食物繊維','自然の活力','おやつ'],k:'スリランカで「ごはんの木」と呼ばれるジャックフルーツの木の、熟した実からつくります。'},
 ],
};

BOOK.si.farm={
 label:'අපේ ගොවිපොළවල් · Our Farms',
 title:'පොළොවේ සිට<br>ඔබ දක්වා',
 sub:'අපේම කාබනික ගොවිපොළවල්',
 intro:'මේ පොතේ කතා කරන සෑම දෙයක්ම ආරම්භ වන්නේ මෙතැනිනි — නුවර, ගලහ අපේ හරිතාගාරයේ සහ අනුරාධපුර අපේ කාබනික ගොවිපොළේ. මේවා ඇත්තම පින්තූර.',
 caps:[
  {t:'ගලහ, නුවර — අපේ හරිතාගාරය',s:'තක්කාලි, නෝකෝල් සහ තවත් එළවළු, රසායනික නොවන පසේ පේළි ගැසී.'},
  {t:'පැළ තවාන',s:'සෑම වගාවක්ම ආරම්භ වන්නේ මෙතැනිනි — නිරෝගී පැළ, ට්‍රේ තුළ රැකවරණය සහිතව.'},
  {t:'බීට්රූට්',s:'රතු නාරටි සහිත නැවුම් කොළ — වස විෂෙන් තොරව වැඩුණු.'},
  {t:'එළවළු පේළි',s:'තක්කාලි, නෝකෝල් සහ පිපිඤ්ඤා එකම හරිතාගාරයේ, සොබාදහමේ රිද්මයට.'},
  {t:'ගස්ලබු — අනුරාධපුර ගොවිපොළ',s:'විවෘත අහස යට, රතු පසේ ඉදෙන කාබනික ගස්ලබු.'},
  {t:'ගස්ලබු හා කෙසෙල් එකට',s:'විවිධ වගාව එකට — පස පෝෂණය කරමින්, ස්වාභාවික සමතුලිතතාව රකිමින්.'},
  {t:'ඉරිඟු',s:'විවෘත අහස යට, රසායනික නොවන ඉරිඟු වගාව නැවුම්ව.'},
 ],
};
BOOK.en.farm={
 label:'Our Farms',
 title:'From our soil<br>to you',
 sub:'Our own organic farms',
 intro:'Everything this book speaks of begins here — at our green house in Galaha, Kandy, and our organic farm in Anuradhapura. These are real photographs.',
 caps:[
  {t:'Galaha, Kandy — our green house',s:'Tomato, knol-khol and more, in neat rows of chemical-free soil.'},
  {t:'The nursery',s:'Every crop begins here — healthy seedlings, sheltered in their trays.'},
  {t:'Beetroot',s:'Fresh red-veined leaves, grown free of poison.'},
  {t:'Rows of vegetables',s:'Tomato, knol-khol and cucumber under one roof, to nature\'s rhythm.'},
  {t:'Papaya — Anuradhapura farm',s:'Organic papaya ripening in red earth, under an open sky.'},
  {t:'Papaya & banana together',s:'Mixed planting — feeding the soil and keeping nature in balance.'},
  {t:'Maize',s:'Chemical-free maize, fresh under the open sky.'},
 ],
};
BOOK.ta.farm={
 label:'எங்கள் பண்ணைகள் · Our Farms',
 title:'எங்கள் மண்ணிலிருந்து<br>உங்களுக்கு',
 sub:'எங்கள் சொந்த இயற்கைப் பண்ணைகள்',
 intro:'இந்த நூல் பேசும் அனைத்தும் இங்கிருந்தே தொடங்குகின்றன — கண்டி, கலஹாவில் உள்ள எங்கள் பசுமை இல்லத்திலும், அனுராதபுரத்தில் உள்ள எங்கள் இயற்கைப் பண்ணையிலும். இவை உண்மையான புகைப்படங்கள்.',
 caps:[
  {t:'கலஹா, கண்டி — எங்கள் பசுமை இல்லம்',s:'தக்காளி, நோல்கோல் மற்றும் பல, இரசாயனமற்ற மண்ணின் நேர்த்தியான வரிசைகளில்.'},
  {t:'நாற்றங்கால்',s:'ஒவ்வொரு பயிரும் இங்கிருந்தே தொடங்குகிறது — தட்டுகளில் பாதுகாக்கப்பட்ட ஆரோக்கியமான நாற்றுகள்.'},
  {t:'பீட்ரூட்',s:'சிவப்பு நரம்புள்ள புத்தம்புதிய இலைகள், விஷமின்றி வளர்க்கப்பட்டவை.'},
  {t:'காய்கறி வரிசைகள்',s:'தக்காளி, நோல்கோல், வெள்ளரி ஒரே கூரையின் கீழ், இயற்கையின் தாளத்திற்கு.'},
  {t:'பப்பாளி — அனுராதபுரப் பண்ணை',s:'திறந்த வானின் கீழ், சிவப்பு மண்ணில் பழுக்கும் இயற்கைப் பப்பாளி.'},
  {t:'பப்பாளியும் வாழையும் ஒன்றாக',s:'கலப்புப் பயிர் — மண்ணை ஊட்டி, இயற்கையின் சமநிலையைக் காக்கிறது.'},
  {t:'சோளம்',s:'திறந்த வானின் கீழ், இரசாயனமற்ற புத்தம்புதிய சோளம்.'},
 ],
};
BOOK.ja.farm={
 label:'私たちの農園 · Our Farms',
 title:'私たちの土から、<br>あなたへ',
 sub:'私たち自身の有機農園',
 intro:'この本が語るすべては、ここから始まります——キャンディ・ガラハの温室と、アヌラーダプラの有機農園から。これらは本物の写真です。',
 caps:[
  {t:'ガラハ（キャンディ）— 私たちの温室',s:'トマト、コールラビ、そのほか——化学物質を使わない土のきれいな畝に。'},
  {t:'苗床',s:'どの作物もここから始まります——トレイでまもられた、健やかな苗。'},
  {t:'ビーツ',s:'赤い葉脈のみずみずしい葉。毒を使わずに育てました。'},
  {t:'野菜の畝',s:'トマト、コールラビ、きゅうりをひとつ屋根の下で、自然のリズムに沿って。'},
  {t:'パパイヤ — アヌラーダプラ農園',s:'開けた空の下、赤い土で実る有機パパイヤ。'},
  {t:'パパイヤとバナナをともに',s:'混植——土を養い、自然のバランスを保ちます。'},
  {t:'とうもろこし',s:'開けた空の下、化学物質を使わないみずみずしいとうもろこし。'},
 ],
};
