/* Recipes chapter. Ingredients starting with * are Kenko 1st Organic products (shown in green). */
BOOK.si.recipes={label:'වට්ටෝරු · Recipes',title:'කාබනික<br>කුස්සිය',sub:'අපේ නිෂ්පාදන සමඟ සරල දේශීය කෑම',intro:'මෙම පොතේ ඇති ඖෂධ පැළෑටි සහ ආහාර එදිනෙදා කෑම වේලට එක් කරගන්නා සරල, සාම්ප්‍රදායික වට්ටෝරු හතරක්.',labIng:'අවශ්‍ය දෑ',labSteps:'සාදන ආකාරය',labTip:'ඉඟිය',note:'කොළ පාටින් ඇති දෑ Kenko 1st Organic හි ලබාගත හැක.',items:[
{n:'මුරුංගා කොළ කැඳ',en:'Moringa Kola Kenda',m:['විනාඩි 35','දෙදෙනෙකුට'],ing:['*සුවඳැල් හාල් කෝප්ප ½','*මුරුංගා කුඩු තේ හැඳි 2','ඝන පොල්කිරි කෝප්ප 1','වතුර කෝප්ප 3','සුදුළූණු බික් 2','ලුණු රසට','*කිතුල් පැණි (සමඟ කෑමට)'],st:['හාල් සෝදා, වතුර හා සුදුළූණු සමඟ හොඳින් පෙඟෙන තෙක් (විනාඩි 25 පමණ) තම්බන්න.','පොල්කිරි එක් කර, අඩු ගින්නේ විනාඩි 3–4ක් කලතන්න.','ගින්න නිවා, මුරුංගා කුඩු සහ ලුණු එක් කර කලතන්න.','උණුසුම්ව, හකුරු කැබැල්ලක් හෝ කිතුල් පැණි සමඟ පිළිගන්වන්න.'],tip:'මුරුංගා කුඩු ගින්න නිවූ පසු එක් කිරීමෙන් එහි විටමින් ආරක්ෂා වේ.'},
{n:'මුං කිරිබත්',en:'Mung Kiribath',m:['විනාඩි 50','හතර දෙනෙකුට'],ing:['*සුවඳැල් හාල් කෝප්ප 2','*කාබනික මුං ඇට කෝප්ප ½','ඝන පොල්කිරි කෝප්ප 1½','වතුර කෝප්ප 4','ලුණු තේ හැඳි 1'],st:['මුං ඇට සැහැල්ලුවට බැද, පැයක් පොඟවා ගන්න.','හාල් හා මුං ඇට වතුර සමඟ මෘදු වන තෙක් තම්බන්න.','පොල්කිරි සහ ලුණු එක් කර, ඝන වන තෙක් අඩු ගින්නේ කලතන්න.','පිඟානක දමා සමතලා කර, ටිකක් නිවුණු පසු දියමන්ති හැඩයට කපන්න.'],tip:'ලුනු මිරිස් හෝ කිතුල් පැණි සමඟ රසවත්ම වේ.'},
{n:'කුරක්කන් රොටි',en:'Kurakkan Roti',m:['විනාඩි 30','රොටි 8ක්'],ing:['*කුරක්කන් පිටි කෝප්ප 2','ගෑ පොල් කෝප්ප 1','රතු ළූණු 1 (කපාගත්)','අමු මිරිස් 2 (කපාගත්)','කරපිංචා ටිකක්','ලුණු රසට','වතුර අවශ්‍ය පරිදි'],st:['පිටි, පොල්, ළූණු, මිරිස්, කරපිංචා සහ ලුණු හොඳින් මිශ්‍ර කරන්න.','වතුර ටික ටික එක් කර මෘදු පිටි ගුලියක් සාදා ගන්න.','කුඩා ගුලි කර, කෙසෙල් කොළයක් මත අතින් තලා සමතලා කරන්න.','රත් වූ තාච්චියේ එක් පැත්තකට විනාඩි 3–4 බැගින් පුළුස්සන්න.'],tip:'තන්තු සහ කැල්සියම් බහුල උදෑසන ආහාරයකි. පොල් සම්බෝල සමඟ කන්න.'},
{n:'රණවරා ඉඟුරු තේ',en:'Ranawara & Ginger Tea',m:['විනාඩි 10','එක් අයෙකුට'],ing:['*රණවරා මල් කුඩු තේ හැඳි 1','*කාබනික ඉඟුරු කුඩු තේ හැඳි ¼','*කාබනික කුරුඳු කුඩු ස්වල්පයක්','වතුර කෝප්ප 1½','*මී පැණි තේ හැඳි 1'],st:['වතුර උතුරවා ගන්න.','රණවරා, ඉඟුරු සහ කුරුඳු එක් කර අඩු ගින්නේ විනාඩි 3–4ක් තබන්න.','පෙරා කෝප්පයකට දමා ටිකක් නිවෙන්න දෙන්න.','මී පැණි එක් කර කලතා බොන්න.'],tip:'ඉතා උණු වතුරේ මී පැණි එහි ගුණ නැති කරයි. ටිකක් නිවුණු පසු එක් කරන්න.'}]};

BOOK.en.recipes={label:'Recipes',title:'The organic<br>kitchen',sub:'Simple Sri Lankan dishes with our produce',intro:'Four simple, traditional recipes that bring the herbs and foods in this book into your everyday meals.',labIng:'You will need',labSteps:'Method',labTip:'Tip',note:'Ingredients in green are available at Kenko 1st Organic.',items:[
{n:'Moringa Kola Kenda',en:'Herbal porridge',m:['35 min','Serves 2'],ing:['*Suwandal rice ½ cup','*Moringa powder 2 tsp','Thick coconut milk 1 cup','Water 3 cups','Garlic 2 cloves','Salt to taste','*Kithul treacle, to serve'],st:['Wash the rice and boil it with the water and garlic until very soft, about 25 minutes.','Add the coconut milk and stir over low heat for 3–4 minutes.','Turn off the heat, then stir in the moringa powder and salt.','Serve warm with a piece of jaggery or a drizzle of kithul treacle.'],tip:'Adding moringa after the heat is off protects its vitamins.'},
{n:'Mung Kiribath',en:'Green gram milk rice',m:['50 min','Serves 4'],ing:['*Suwandal rice 2 cups','*Organic green gram ½ cup','Thick coconut milk 1½ cups','Water 4 cups','Salt 1 tsp'],st:['Lightly dry-roast the green gram, then soak it for an hour.','Cook the rice and green gram in the water until soft.','Add the coconut milk and salt, and stir over low heat until thick.','Spread on a plate, flatten, and cut into diamonds once slightly cool.'],tip:'Best with lunu miris or kithul treacle.'},
{n:'Kurakkan Roti',en:'Finger millet flatbread',m:['30 min','Makes 8'],ing:['*Kurakkan flour 2 cups','Grated coconut 1 cup','Red onion 1, chopped','Green chillies 2, chopped','A few curry leaves','Salt to taste','Water as needed'],st:['Mix the flour, coconut, onion, chillies, curry leaves and salt.','Add water a little at a time and knead into a soft dough.','Divide into small balls and pat each flat on a banana leaf.','Cook on a hot pan for 3–4 minutes on each side.'],tip:'A breakfast rich in fibre and calcium. Serve with pol sambol.'},
{n:'Ranawara & Ginger Tea',en:'Herbal tea with honey',m:['10 min','Serves 1'],ing:['*Ranawara flower powder 1 tsp','*Organic ginger powder ¼ tsp','*Organic cinnamon powder, a pinch','Water 1½ cups','*Bee honey 1 tsp'],st:['Bring the water to the boil.','Add the ranawara, ginger and cinnamon, and simmer on low for 3–4 minutes.','Strain into a cup and let it cool slightly.','Stir in the honey and enjoy.'],tip:'Very hot water destroys the goodness of honey, so add it once the tea has cooled a little.'}]};

BOOK.ta.recipes={label:'சமையல் குறிப்புகள் · Recipes',title:'இயற்கை<br>சமையலறை',sub:'எங்கள் பொருட்களுடன் எளிய உள்நாட்டு உணவுகள்',intro:'இந்த நூலில் உள்ள மூலிகைகளையும் உணவுகளையும் அன்றாட உணவில் சேர்க்க உதவும் நான்கு எளிய, பாரம்பரிய சமையல் குறிப்புகள்.',labIng:'தேவையானவை',labSteps:'செய்முறை',labTip:'குறிப்பு',note:'பச்சை நிறத்தில் உள்ளவை Kenko 1st Organic-இல் கிடைக்கும்.',items:[
{n:'முருங்கை கொள கஞ்சி',en:'Moringa Kola Kenda',m:['35 நிமிடம்','2 பேருக்கு'],ing:['*சுவந்தல் அரிசி ½ கோப்பை','*முருங்கைப் பொடி 2 தேக்கரண்டி','கெட்டியான தேங்காய்ப் பால் 1 கோப்பை','தண்ணீர் 3 கோப்பை','பூண்டு 2 பல்','உப்பு தேவைக்கு','*கித்துல் பாணி (பரிமாற)'],st:['அரிசியைக் கழுவி, தண்ணீர், பூண்டுடன் நன்கு குழையும் வரை (சுமார் 25 நிமிடம்) வேகவிடவும்.','தேங்காய்ப் பால் சேர்த்து, மிதமான தீயில் 3–4 நிமிடம் கிளறவும்.','அடுப்பை அணைத்து, முருங்கைப் பொடி, உப்பு சேர்த்துக் கிளறவும்.','சூடாக, வெல்லத் துண்டு அல்லது கித்துல் பாணியுடன் பரிமாறவும்.'],tip:'அடுப்பை அணைத்த பின் முருங்கைப் பொடியைச் சேர்ப்பதால் அதன் வைட்டமின்கள் காக்கப்படுகின்றன.'},
{n:'பாசிப்பயறு பாற்சோறு',en:'Mung Kiribath',m:['50 நிமிடம்','4 பேருக்கு'],ing:['*சுவந்தல் அரிசி 2 கோப்பை','*இயற்கை பாசிப்பயறு ½ கோப்பை','கெட்டியான தேங்காய்ப் பால் 1½ கோப்பை','தண்ணீர் 4 கோப்பை','உப்பு 1 தேக்கரண்டி'],st:['பாசிப்பயறை லேசாக வறுத்து, ஒரு மணி நேரம் ஊறவைக்கவும்.','அரிசியையும் பயறையும் தண்ணீருடன் மென்மையாகும் வரை வேகவிடவும்.','தேங்காய்ப் பால், உப்பு சேர்த்து, கெட்டியாகும் வரை மிதமான தீயில் கிளறவும்.','தட்டில் பரப்பி சமன் செய்து, சற்று ஆறியதும் வைர வடிவில் வெட்டவும்.'],tip:'லுணு மிரிஸ் அல்லது கித்துல் பாணியுடன் மிகவும் சுவையாக இருக்கும்.'},
{n:'குரக்கன் ரொட்டி',en:'Kurakkan Roti',m:['30 நிமிடம்','8 ரொட்டிகள்'],ing:['*குரக்கன் மா 2 கோப்பை','துருவிய தேங்காய் 1 கோப்பை','சின்ன வெங்காயம் 1 (நறுக்கியது)','பச்சை மிளகாய் 2 (நறுக்கியது)','கறிவேப்பிலை சிறிது','உப்பு தேவைக்கு','தண்ணீர் தேவைக்கு'],st:['மா, தேங்காய், வெங்காயம், மிளகாய், கறிவேப்பிலை, உப்பு ஆகியவற்றை நன்கு கலக்கவும்.','தண்ணீரைச் சிறிது சிறிதாகச் சேர்த்து மென்மையான மாவாகப் பிசையவும்.','சிறு உருண்டைகளாக்கி, வாழை இலையில் கையால் தட்டவும்.','சூடான தோசைக்கல்லில் ஒவ்வொரு பக்கமும் 3–4 நிமிடம் சுடவும்.'],tip:'நார்ச்சத்தும் கால்சியமும் நிறைந்த காலை உணவு. தேங்காய் சம்பலுடன் உண்ணுங்கள்.'},
{n:'ரணவரா இஞ்சி தேநீர்',en:'Ranawara & Ginger Tea',m:['10 நிமிடம்','1 நபருக்கு'],ing:['*ரணவரா பூப் பொடி 1 தேக்கரண்டி','*இயற்கை இஞ்சிப் பொடி ¼ தேக்கரண்டி','*இயற்கை கறுவாப் பொடி சிட்டிகை','தண்ணீர் 1½ கோப்பை','*தேன் 1 தேக்கரண்டி'],st:['தண்ணீரைக் கொதிக்கவிடவும்.','ரணவரா, இஞ்சி, கறுவா சேர்த்து மிதமான தீயில் 3–4 நிமிடம் வைக்கவும்.','வடிகட்டி கோப்பையில் ஊற்றி, சற்று ஆறவிடவும்.','தேன் சேர்த்துக் கலக்கிப் பருகவும்.'],tip:'மிகச் சூடான நீரில் தேன் தன் பயன்களை இழக்கும். சற்று ஆறிய பின் சேர்க்கவும்.'}]};

BOOK.ja.recipes={label:'レシピ · Recipes',title:'オーガニック<br>キッチン',sub:'私たちの食材でつくる、やさしいスリランカ家庭料理',intro:'この本で紹介したハーブや食材を毎日の食事にとり入れるための、かんたんで伝統的なレシピを4つご紹介します。',labIng:'材料',labSteps:'つくり方',labTip:'ポイント',note:'緑色の材料は Kenko 1st Organic でお求めいただけます。',items:[
{n:'モリンガのコラ・ケンダ',en:'Moringa Kola Kenda（薬草がゆ）',m:['35分','2人分'],ing:['*スワンダル米 1/2カップ','*モリンガパウダー 小さじ2','濃いココナッツミルク 1カップ','水 3カップ','にんにく 2かけ','塩 少々','*キトゥル・トリークル（添える用）'],st:['米を洗い、水とにんにくを加えて、やわらかくなるまで約25分煮ます。','ココナッツミルクを加え、弱火で3〜4分混ぜます。','火を止めてから、モリンガパウダーと塩を加えて混ぜます。','温かいうちに、ジャガリーやキトゥル・トリークルを添えてどうぞ。'],tip:'火を止めてからモリンガを加えると、ビタミンが守られます。'},
{n:'緑豆のキリバット',en:'Mung Kiribath（ミルクライス）',m:['50分','4人分'],ing:['*スワンダル米 2カップ','*有機緑豆 1/2カップ','濃いココナッツミルク 1と1/2カップ','水 4カップ','塩 小さじ1'],st:['緑豆を軽くから煎りし、1時間水に浸します。','米と緑豆を水でやわらかくなるまで炊きます。','ココナッツミルクと塩を加え、とろみがつくまで弱火で混ぜます。','皿に広げて平らにし、少し冷めたらひし形に切ります。'],tip:'ルヌミリス（唐辛子と玉ねぎの薬味）やキトゥル・トリークルとよく合います。'},
{n:'クラッカン・ロティ',en:'Kurakkan Roti（シコクビエのパン）',m:['30分','8枚分'],ing:['*クラッカン（シコクビエ）粉 2カップ','すりおろしココナッツ 1カップ','赤玉ねぎ 1個（みじん切り）','青唐辛子 2本（みじん切り）','カレーリーフ 少々','塩 少々','水 適量'],st:['粉、ココナッツ、玉ねぎ、唐辛子、カレーリーフ、塩をよく混ぜます。','水を少しずつ加え、やわらかい生地にこねます。','小さく丸め、バナナの葉の上で手で平らにのばします。','熱したフライパンで、片面3〜4分ずつ焼きます。'],tip:'食物繊維とカルシウムがゆたかな朝ごはんです。ポル・サンボルと一緒にどうぞ。'},
{n:'ラナワラとしょうがのハーブティー',en:'Ranawara & Ginger Tea',m:['10分','1人分'],ing:['*ラナワラ花パウダー 小さじ1','*有機しょうがパウダー 小さじ1/4','*有機シナモンパウダー ひとつまみ','水 1と1/2カップ','*はちみつ 小さじ1'],st:['お湯をわかします。','ラナワラ、しょうが、シナモンを入れ、弱火で3〜4分煮出します。','こしてカップに注ぎ、少し冷まします。','はちみつを加えて混ぜ、お召し上がりください。'],tip:'熱すぎるお湯でははちみつの栄養がそこなわれます。少し冷めてから加えましょう。'}]};

BOOK.si.recipes.items.push(
{n:'රතු කව්පි කරිය',en:'Red Cowpea Curry',m:['විනාඩි 40','හතර දෙනෙකුට'],ing:['*කාබනික රතු කව්පි කෝප්ප 1','රතු ළූණු 1 (කපාගත්)','සුදුළූණු බික් 3','අමු මිරිස් 2','තුනපහ තේ හැඳි 1','කහ තේ හැඳි ¼','*කාබනික කුරුඳු කුඩු ස්වල්පයක්','පොල්කිරි කෝප්ප 1','කරපිංචා, ලුණු රසට'],st:['කව්පි රාත්‍රිය පුරා පොඟවා, මෘදු වන තෙක් තම්බා ගන්න.','ළූණු, සුදුළූණු, මිරිස් සහ කරපිංචා තෙල් ස්වල්පයක බැද ගන්න.','කව්පි, තුනපහ, කහ සහ කුරුඳු එක් කර මිශ්‍ර කරන්න.','පොල්කිරි සහ ලුණු එක් කර අඩු ගින්නේ විනාඩි 10ක් උයන්න.'],tip:'ප්‍රෝටීන් සහ තන්තු බහුලයි. බත් හෝ කුරක්කන් රොටි සමඟ කන්න.'},
{n:'හබල පෙති හා වියළි පලතුරු',en:'Rice Flakes Breakfast Bowl',m:['විනාඩි 10','එක් අයෙකුට'],ing:['*හබල පෙති කෝප්ප ½','උණු කිරි හෝ පොල්කිරි කෝප්ප ¾','*වියළි අඹ මේස හැඳි 1','*වියළි අන්නාසි මේස හැඳි 1','*වියළි කෙසෙල් මේස හැඳි 1','ගෑ පොල් මේස හැඳි 2','*මී පැණි තේ හැඳි 1'],st:['හබල පෙති වතුරෙන් සෝදා පෙරා ගන්න.','උණු කිරිවල විනාඩි 5ක් පොඟවන්න.','ගෑ පොල් එක් කර, කපාගත් වියළි පලතුරු උඩින් දමන්න.','මී පැණි ඉස පිළිගන්වන්න.'],tip:'ඉක්මන්, ශක්තිය දෙන උදෑසන ආහාරයකි. දරුවන්ගේ කෑම පෙට්ටියටත් සුදුසුයි.'},
{n:'කිතුල් තලප',en:'Kithul Thalapa',m:['විනාඩි 25','හය දෙනෙකුට'],ing:['*කිතුල් පිටි කෝප්ප ½','ඝන පොල්කිරි කෝප්ප 2','*කිතුල් පැණි කෝප්ප ¼','එනසාල් කරල් 2','ලුණු ස්වල්පයක්'],st:['කිතුල් පිටි, පොල්කිරි ස්වල්පයක් සමඟ ගුලි නැතිව දිය කරන්න.','ඉතිරි පොල්කිරි, කිතුල් පැණි, එනසාල් සහ ලුණු රත් කරන්න.','පිටි මිශ්‍රණය එක් කර, ඝන වී දිලිසෙන තෙක් (විනාඩි 10–15) නොනවත්වා කලතන්න.','පිඟානකට වත්කර, නිවුණු පසු කැබලි කපන්න.'],tip:'නොනවත්වා කලතන එක වැදගත්. එවිට මිශ්‍රණය යට ඇලෙන්නේ නැහැ.'},
{n:'ඉරමුසු පොල්පලා පානය',en:'Iramusu & Polpala Drink',m:['විනාඩි 15','දෙදෙනෙකුට'],ing:['*ඉරමුසු කුඩු තේ හැඳි 1','*පොල්පලා කුඩු තේ හැඳි ½','වතුර කෝප්ප 2','*කිතුල් පැණි හෝ මී පැණි රසට'],st:['වතුර උතුරවා ගන්න.','ඉරමුසු සහ පොල්පලා කුඩු එක් කරන්න.','අඩු ගින්නේ කෝප්ප එකක් පමණ වන තෙක් (විනාඩි 10) තබන්න.','පෙරා, ටිකක් නිවුණු පසු පැණි එක් කර බොන්න.'],tip:'සාම්ප්‍රදායිකව රස්නෙ දවස්වල සිසිලස සඳහා බොන පානයකි.'});
BOOK.en.recipes.items.push(
{n:'Red Cowpea Curry',en:'Rathu kawpi curry',m:['40 min','Serves 4'],ing:['*Organic red cowpea 1 cup','Red onion 1, chopped','Garlic 3 cloves','Green chillies 2','Curry powder 1 tsp','Turmeric ¼ tsp','*Organic cinnamon powder, a pinch','Coconut milk 1 cup','Curry leaves, salt to taste'],st:['Soak the cowpeas overnight, then boil until soft.','Fry the onion, garlic, chillies and curry leaves in a little oil.','Add the cowpeas, curry powder, turmeric and cinnamon, and mix well.','Add the coconut milk and salt, and simmer on low for 10 minutes.'],tip:'Rich in protein and fibre. Serve with rice or kurakkan roti.'},
{n:'Rice Flakes Breakfast Bowl',en:'With dried fruit and honey',m:['10 min','Serves 1'],ing:['*Rice flakes ½ cup','Warm milk or coconut milk ¾ cup','*Dried mango 1 tbsp','*Dried pineapple 1 tbsp','*Dried banana 1 tbsp','Grated coconut 2 tbsp','*Bee honey 1 tsp'],st:['Rinse the rice flakes and drain.','Soak them in the warm milk for 5 minutes.','Add the grated coconut and top with the chopped dried fruit.','Drizzle with honey and serve.'],tip:'A quick, energising breakfast that also suits a school lunch box.'},
{n:'Kithul Thalapa',en:'Kithul flour pudding',m:['25 min','Serves 6'],ing:['*Kithul flour ½ cup','Thick coconut milk 2 cups','*Kithul treacle ¼ cup','Cardamom 2 pods','A pinch of salt'],st:['Mix the kithul flour with a little coconut milk until smooth, with no lumps.','Heat the rest of the coconut milk with the treacle, cardamom and salt.','Add the flour mixture and stir without stopping until thick and glossy, 10–15 minutes.','Pour into a dish and cut into pieces once cool.'],tip:'Keep stirring the whole time so it does not stick to the pan.'},
{n:'Iramusu & Polpala Drink',en:'Traditional herbal drink',m:['15 min','Serves 2'],ing:['*Iramusu powder 1 tsp','*Polpala powder ½ tsp','Water 2 cups','*Kithul treacle or honey, to taste'],st:['Bring the water to the boil.','Add the iramusu and polpala powders.','Simmer on low until reduced to about 1 cup, around 10 minutes.','Strain, let it cool a little, then sweeten and drink.'],tip:'Traditionally drunk to cool the body on hot days.'});
BOOK.ta.recipes.items.push(
{n:'சிவப்பு காராமணி கறி',en:'Red Cowpea Curry',m:['40 நிமிடம்','4 பேருக்கு'],ing:['*இயற்கை சிவப்பு காராமணி 1 கோப்பை','சின்ன வெங்காயம் 1 (நறுக்கியது)','பூண்டு 3 பல்','பச்சை மிளகாய் 2','கறித்தூள் 1 தேக்கரண்டி','மஞ்சள் ¼ தேக்கரண்டி','*இயற்கை கறுவாப் பொடி சிட்டிகை','தேங்காய்ப் பால் 1 கோப்பை','கறிவேப்பிலை, உப்பு தேவைக்கு'],st:['காராமணியை இரவு முழுவதும் ஊறவைத்து, மென்மையாகும் வரை வேகவிடவும்.','வெங்காயம், பூண்டு, மிளகாய், கறிவேப்பிலையைச் சிறிது எண்ணெயில் வதக்கவும்.','காராமணி, கறித்தூள், மஞ்சள், கறுவா சேர்த்துக் கலக்கவும்.','தேங்காய்ப் பால், உப்பு சேர்த்து மிதமான தீயில் 10 நிமிடம் வேகவிடவும்.'],tip:'புரதமும் நார்ச்சத்தும் நிறைந்தது. சோறு அல்லது குரக்கன் ரொட்டியுடன் உண்ணுங்கள்.'},
{n:'அவல் உலர்பழக் கிண்ணம்',en:'Rice Flakes Breakfast Bowl',m:['10 நிமிடம்','1 நபருக்கு'],ing:['*அவல் ½ கோப்பை','சூடான பால் அல்லது தேங்காய்ப் பால் ¾ கோப்பை','*உலர் மாம்பழம் 1 மேசைக்கரண்டி','*உலர் அன்னாசி 1 மேசைக்கரண்டி','*உலர் வாழைப்பழம் 1 மேசைக்கரண்டி','துருவிய தேங்காய் 2 மேசைக்கரண்டி','*தேன் 1 தேக்கரண்டி'],st:['அவலைக் கழுவி வடிகட்டவும்.','சூடான பாலில் 5 நிமிடம் ஊறவைக்கவும்.','தேங்காய் சேர்த்து, நறுக்கிய உலர்பழங்களை மேலே தூவவும்.','தேன் ஊற்றிப் பரிமாறவும்.'],tip:'விரைவான, சக்தி தரும் காலை உணவு. பிள்ளைகளின் உணவுப் பெட்டிக்கும் ஏற்றது.'},
{n:'கித்துல் தலப',en:'Kithul Thalapa',m:['25 நிமிடம்','6 பேருக்கு'],ing:['*கித்துல் மா ½ கோப்பை','கெட்டியான தேங்காய்ப் பால் 2 கோப்பை','*கித்துல் பாணி ¼ கோப்பை','ஏலக்காய் 2','உப்பு சிட்டிகை'],st:['கித்துல் மாவைச் சிறிது தேங்காய்ப் பாலுடன் கட்டியின்றிக் கரைக்கவும்.','மீதித் தேங்காய்ப் பால், கித்துல் பாணி, ஏலக்காய், உப்பைச் சூடாக்கவும்.','மாக் கலவையைச் சேர்த்து, கெட்டியாகிப் பளபளக்கும் வரை (10–15 நிமிடம்) நிறுத்தாமல் கிளறவும்.','தட்டில் ஊற்றி, ஆறியதும் துண்டுகளாக வெட்டவும்.'],tip:'நிறுத்தாமல் கிளறுவது முக்கியம். அப்போது அடியில் ஒட்டாது.'},
{n:'இராமுசு பொல்பலா பானம்',en:'Iramusu & Polpala Drink',m:['15 நிமிடம்','2 பேருக்கு'],ing:['*இராமுசு பொடி 1 தேக்கரண்டி','*பொல்பலா பொடி ½ தேக்கரண்டி','தண்ணீர் 2 கோப்பை','*கித்துல் பாணி அல்லது தேன் தேவைக்கு'],st:['தண்ணீரைக் கொதிக்கவிடவும்.','இராமுசு, பொல்பலா பொடிகளைச் சேர்க்கவும்.','ஏறக்குறைய 1 கோப்பை ஆகும் வரை (10 நிமிடம்) மிதமான தீயில் வைக்கவும்.','வடிகட்டி, சற்று ஆறியதும் இனிப்புச் சேர்த்துப் பருகவும்.'],tip:'வெப்பமான நாட்களில் உடலைக் குளிர்விக்கப் பாரம்பரியமாக அருந்தப்படும் பானம்.'});
BOOK.ja.recipes.items.push(
{n:'赤ササゲ豆のカレー',en:'Red Cowpea Curry',m:['40分','4人分'],ing:['*有機赤ササゲ豆 1カップ','赤玉ねぎ 1個（みじん切り）','にんにく 3かけ','青唐辛子 2本','カレーパウダー 小さじ1','ターメリック 小さじ1/4','*有機シナモンパウダー ひとつまみ','ココナッツミルク 1カップ','カレーリーフ、塩 少々'],st:['豆をひと晩水に浸し、やわらかくなるまでゆでます。','玉ねぎ、にんにく、唐辛子、カレーリーフを少しの油で炒めます。','豆、カレーパウダー、ターメリック、シナモンを加えて混ぜます。','ココナッツミルクと塩を加え、弱火で10分煮ます。'],tip:'たんぱく質と食物繊維がゆたかです。ごはんやクラッカン・ロティと一緒にどうぞ。'},
{n:'ライスフレークの朝ごはんボウル',en:'Rice Flakes Breakfast Bowl',m:['10分','1人分'],ing:['*ライスフレーク 1/2カップ','温かい牛乳またはココナッツミルク 3/4カップ','*ドライマンゴー 大さじ1','*ドライパイナップル 大さじ1','*ドライバナナ 大さじ1','すりおろしココナッツ 大さじ2','*はちみつ 小さじ1'],st:['ライスフレークを水で洗い、水気を切ります。','温かい牛乳に5分ひたします。','ココナッツを加え、刻んだドライフルーツをのせます。','はちみつをかけてどうぞ。'],tip:'手早くできて元気が出る朝ごはん。お弁当にもぴったりです。'},
{n:'キトゥル・タラパ',en:'Kithul Thalapa（キトゥル粉のプディング）',m:['25分','6人分'],ing:['*キトゥル粉 1/2カップ','濃いココナッツミルク 2カップ','*キトゥル・トリークル 1/4カップ','カルダモン 2粒','塩 ひとつまみ'],st:['キトゥル粉を少量のココナッツミルクで、だまがないように溶きます。','残りのココナッツミルク、トリークル、カルダモン、塩を温めます。','粉を溶いたものを加え、とろみとつやが出るまで10〜15分混ぜ続けます。','器に流し入れ、冷めたら切り分けます。'],tip:'手を止めずに混ぜ続けると、鍋底にこげつきません。'},
{n:'イラムスとポルパラの飲みもの',en:'Iramusu & Polpala Drink',m:['15分','2人分'],ing:['*イラムスパウダー 小さじ1','*ポルパラパウダー 小さじ1/2','水 2カップ','*キトゥル・トリークルまたははちみつ 適量'],st:['お湯をわかします。','イラムスとポルパラのパウダーを加えます。','弱火で約1カップになるまで10分ほど煮出します。','こして少し冷まし、甘みを加えてお飲みください。'],tip:'暑い日に体を冷やすため、昔から飲まれてきた飲みものです。'});
BOOK.si.recipes.intro=BOOK.si.recipes.intro.replace('හතරක්','අටක්');
BOOK.en.recipes.intro=BOOK.en.recipes.intro.replace('Four','Eight');
BOOK.ta.recipes.intro=BOOK.ta.recipes.intro.replace('நான்கு','எட்டு');
BOOK.ja.recipes.intro=BOOK.ja.recipes.intro.replace('4つ','8つ');

BOOK.si.recipes.cta={kick:'තවත් වට්ටෝරු',title:'රසවත් වට්ටෝරු පොත නොමිලේ',p:'තවත් රසවත් කාබනික වට්ටෝරු රැසක් ඇතුළත් අපේ අලුත් වට්ටෝරු ඊ-පොත ළඟදීම එනවා. ඔබේ නම සහ නගරය ඇතුළත් කර පහත බොත්තම ඔබන්න. පොත ලැබුණු විගස මුලින්ම ඔබට එවන්නෙමු.',name:'ඔබේ නම',city:'ඔබේ නගරය',btn:'WhatsApp හරහා එවන්න',note:'පොත ඔබේ WhatsApp අංකයට එවනු ලැබේ.',err:'කරුණාකර නම සහ නගරය ඇතුළත් කරන්න.',msg:(n,c)=>'ආයුබෝවන් Kenko 1st Organic, මට අලුත් වට්ටෝරු ඊ-පොත එවන්න.\nනම: '+n+'\nනගරය: '+c};
BOOK.en.recipes.cta={kick:'More recipes',title:'Get our free recipe book',p:'Our new recipe e-book, full of more tasty organic recipes, is coming soon. Enter your name and town and tap the button below, and we will send it to you first.',name:'Your name',city:'Your town',btn:'Send on WhatsApp',note:'We will send the book to your WhatsApp number.',err:'Please enter your name and town.',msg:(n,c)=>'Hello Kenko 1st Organic, please send me the new recipe e-book.\nName: '+n+'\nTown: '+c};
BOOK.ta.recipes.cta={kick:'மேலும் சமையல் குறிப்புகள்',title:'இலவச சமையல் நூலைப் பெறுங்கள்',p:'மேலும் பல சுவையான இயற்கை சமையல் குறிப்புகளுடன் எங்கள் புதிய சமையல் மின்னூல் விரைவில் வருகிறது. உங்கள் பெயரையும் ஊரையும் உள்ளிட்டு கீழே உள்ள பொத்தானை அழுத்துங்கள். முதலில் உங்களுக்கு அனுப்புவோம்.',name:'உங்கள் பெயர்',city:'உங்கள் ஊர்',btn:'WhatsApp மூலம் அனுப்புங்கள்',note:'நூல் உங்கள் WhatsApp எண்ணுக்கு அனுப்பப்படும்.',err:'தயவுசெய்து பெயரையும் ஊரையும் உள்ளிடவும்.',msg:(n,c)=>'வணக்கம் Kenko 1st Organic, புதிய சமையல் மின்னூலை எனக்கு அனுப்புங்கள்.\nபெயர்: '+n+'\nஊர்: '+c};
BOOK.ja.recipes.cta={kick:'もっとレシピを',title:'無料レシピブックを受け取る',p:'おいしい有機レシピをたっぷり集めた新しいレシピ電子書籍を準備中です。お名前と町名を入力してボタンを押していただければ、いち早くお届けします。',name:'お名前',city:'お住まいの町',btn:'WhatsAppで送る',note:'ご利用のWhatsApp番号にお送りします。',err:'お名前と町名を入力してください。',msg:(n,c)=>'こんにちは Kenko 1st Organic、新しいレシピ電子書籍を送ってください。\nお名前：'+n+'\n町：'+c};
